// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module blockControl173 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        input_V_data_TDATA,
        input_V_data_TVALID,
        input_V_data_TREADY,
        V_SIZE,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        simConfig_rowBegin_V_out_din,
        simConfig_rowBegin_V_out_full_n,
        simConfig_rowBegin_V_out_write,
        simConfig_rowEnd_V_out_din,
        simConfig_rowEnd_V_out_full_n,
        simConfig_rowEnd_V_out_write,
        simConfig_rowsToSimulate_V_out_din,
        simConfig_rowsToSimulate_V_out_full_n,
        simConfig_rowsToSimulate_V_out_write,
        simConfig_BLOCK_NUMBERS_V_out_din,
        simConfig_BLOCK_NUMBERS_V_out_full_n,
        simConfig_BLOCK_NUMBERS_V_out_write,
        V_data_V_data_0_din,
        V_data_V_data_0_full_n,
        V_data_V_data_0_write,
        V_data_V_data_1_din,
        V_data_V_data_1_full_n,
        V_data_V_data_1_write,
        V_data_V_data_2_din,
        V_data_V_data_2_full_n,
        V_data_V_data_2_write,
        V_data_V_data_3_din,
        V_data_V_data_3_full_n,
        V_data_V_data_3_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] input_V_data_TDATA;
input   input_V_data_TVALID;
output   input_V_data_TREADY;
input  [31:0] V_SIZE;
input  [26:0] p_read;
input  [26:0] p_read1;
input  [26:0] p_read2;
input  [26:0] p_read3;
output  [26:0] simConfig_rowBegin_V_out_din;
input   simConfig_rowBegin_V_out_full_n;
output   simConfig_rowBegin_V_out_write;
output  [26:0] simConfig_rowEnd_V_out_din;
input   simConfig_rowEnd_V_out_full_n;
output   simConfig_rowEnd_V_out_write;
output  [26:0] simConfig_rowsToSimulate_V_out_din;
input   simConfig_rowsToSimulate_V_out_full_n;
output   simConfig_rowsToSimulate_V_out_write;
output  [26:0] simConfig_BLOCK_NUMBERS_V_out_din;
input   simConfig_BLOCK_NUMBERS_V_out_full_n;
output   simConfig_BLOCK_NUMBERS_V_out_write;
output  [31:0] V_data_V_data_0_din;
input   V_data_V_data_0_full_n;
output   V_data_V_data_0_write;
output  [31:0] V_data_V_data_1_din;
input   V_data_V_data_1_full_n;
output   V_data_V_data_1_write;
output  [31:0] V_data_V_data_2_din;
input   V_data_V_data_2_full_n;
output   V_data_V_data_2_write;
output  [31:0] V_data_V_data_3_din;
input   V_data_V_data_3_full_n;
output   V_data_V_data_3_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg input_V_data_TREADY;
reg simConfig_rowBegin_V_out_write;
reg simConfig_rowEnd_V_out_write;
reg simConfig_rowsToSimulate_V_out_write;
reg simConfig_BLOCK_NUMBERS_V_out_write;
reg V_data_V_data_0_write;
reg V_data_V_data_1_write;
reg V_data_V_data_2_write;
reg V_data_V_data_3_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    simConfig_rowBegin_V_out_blk_n;
wire    ap_CS_fsm_state2;
reg    simConfig_rowEnd_V_out_blk_n;
reg    simConfig_rowsToSimulate_V_out_blk_n;
reg    simConfig_BLOCK_NUMBERS_V_out_blk_n;
reg    ap_block_state1;
wire    grp_getVoltages_fu_118_ap_start;
wire    grp_getVoltages_fu_118_ap_done;
wire    grp_getVoltages_fu_118_ap_idle;
wire    grp_getVoltages_fu_118_ap_ready;
wire    grp_getVoltages_fu_118_input_V_data_TREADY;
wire   [31:0] grp_getVoltages_fu_118_V_data_V_data_0_din;
wire    grp_getVoltages_fu_118_V_data_V_data_0_write;
wire   [31:0] grp_getVoltages_fu_118_V_data_V_data_1_din;
wire    grp_getVoltages_fu_118_V_data_V_data_1_write;
wire   [31:0] grp_getVoltages_fu_118_V_data_V_data_2_din;
wire    grp_getVoltages_fu_118_V_data_V_data_2_write;
wire   [31:0] grp_getVoltages_fu_118_V_data_V_data_3_din;
wire    grp_getVoltages_fu_118_V_data_V_data_3_write;
reg    grp_getVoltages_fu_118_ap_start_reg;
reg    ap_block_state1_ignore_call33;
reg    ap_block_state2;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_getVoltages_fu_118_ap_start_reg = 1'b0;
end

getVoltages grp_getVoltages_fu_118(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_getVoltages_fu_118_ap_start),
    .ap_done(grp_getVoltages_fu_118_ap_done),
    .ap_idle(grp_getVoltages_fu_118_ap_idle),
    .ap_ready(grp_getVoltages_fu_118_ap_ready),
    .input_V_data_TDATA(input_V_data_TDATA),
    .input_V_data_TVALID(input_V_data_TVALID),
    .input_V_data_TREADY(grp_getVoltages_fu_118_input_V_data_TREADY),
    .V_SIZE(V_SIZE),
    .V_data_V_data_0_din(grp_getVoltages_fu_118_V_data_V_data_0_din),
    .V_data_V_data_0_full_n(V_data_V_data_0_full_n),
    .V_data_V_data_0_write(grp_getVoltages_fu_118_V_data_V_data_0_write),
    .V_data_V_data_1_din(grp_getVoltages_fu_118_V_data_V_data_1_din),
    .V_data_V_data_1_full_n(V_data_V_data_1_full_n),
    .V_data_V_data_1_write(grp_getVoltages_fu_118_V_data_V_data_1_write),
    .V_data_V_data_2_din(grp_getVoltages_fu_118_V_data_V_data_2_din),
    .V_data_V_data_2_full_n(V_data_V_data_2_full_n),
    .V_data_V_data_2_write(grp_getVoltages_fu_118_V_data_V_data_2_write),
    .V_data_V_data_3_din(grp_getVoltages_fu_118_V_data_V_data_3_din),
    .V_data_V_data_3_full_n(V_data_V_data_3_full_n),
    .V_data_V_data_3_write(grp_getVoltages_fu_118_V_data_V_data_3_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((grp_getVoltages_fu_118_ap_done == 1'b0) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_rowEnd_V_out_full_n == 1'b0) | (simConfig_rowBegin_V_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_getVoltages_fu_118_ap_start_reg <= 1'b0;
    end else begin
        if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_getVoltages_fu_118_ap_start_reg <= 1'b1;
        end else if ((grp_getVoltages_fu_118_ap_ready == 1'b1)) begin
            grp_getVoltages_fu_118_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_data_V_data_0_write = grp_getVoltages_fu_118_V_data_V_data_0_write;
    end else begin
        V_data_V_data_0_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_data_V_data_1_write = grp_getVoltages_fu_118_V_data_V_data_1_write;
    end else begin
        V_data_V_data_1_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_data_V_data_2_write = grp_getVoltages_fu_118_V_data_V_data_2_write;
    end else begin
        V_data_V_data_2_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_data_V_data_3_write = grp_getVoltages_fu_118_V_data_V_data_3_write;
    end else begin
        V_data_V_data_3_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((grp_getVoltages_fu_118_ap_done == 1'b0) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_rowEnd_V_out_full_n == 1'b0) | (simConfig_rowBegin_V_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_V_data_TREADY = grp_getVoltages_fu_118_input_V_data_TREADY;
    end else begin
        input_V_data_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((grp_getVoltages_fu_118_ap_done == 1'b0) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_rowEnd_V_out_full_n == 1'b0) | (simConfig_rowBegin_V_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        simConfig_BLOCK_NUMBERS_V_out_blk_n = simConfig_BLOCK_NUMBERS_V_out_full_n;
    end else begin
        simConfig_BLOCK_NUMBERS_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((grp_getVoltages_fu_118_ap_done == 1'b0) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_rowEnd_V_out_full_n == 1'b0) | (simConfig_rowBegin_V_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        simConfig_BLOCK_NUMBERS_V_out_write = 1'b1;
    end else begin
        simConfig_BLOCK_NUMBERS_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        simConfig_rowBegin_V_out_blk_n = simConfig_rowBegin_V_out_full_n;
    end else begin
        simConfig_rowBegin_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((grp_getVoltages_fu_118_ap_done == 1'b0) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_rowEnd_V_out_full_n == 1'b0) | (simConfig_rowBegin_V_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        simConfig_rowBegin_V_out_write = 1'b1;
    end else begin
        simConfig_rowBegin_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        simConfig_rowEnd_V_out_blk_n = simConfig_rowEnd_V_out_full_n;
    end else begin
        simConfig_rowEnd_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((grp_getVoltages_fu_118_ap_done == 1'b0) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_rowEnd_V_out_full_n == 1'b0) | (simConfig_rowBegin_V_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        simConfig_rowEnd_V_out_write = 1'b1;
    end else begin
        simConfig_rowEnd_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        simConfig_rowsToSimulate_V_out_blk_n = simConfig_rowsToSimulate_V_out_full_n;
    end else begin
        simConfig_rowsToSimulate_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((grp_getVoltages_fu_118_ap_done == 1'b0) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_rowEnd_V_out_full_n == 1'b0) | (simConfig_rowBegin_V_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        simConfig_rowsToSimulate_V_out_write = 1'b1;
    end else begin
        simConfig_rowsToSimulate_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((grp_getVoltages_fu_118_ap_done == 1'b0) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_rowEnd_V_out_full_n == 1'b0) | (simConfig_rowBegin_V_out_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign V_data_V_data_0_din = grp_getVoltages_fu_118_V_data_V_data_0_din;

assign V_data_V_data_1_din = grp_getVoltages_fu_118_V_data_V_data_1_din;

assign V_data_V_data_2_din = grp_getVoltages_fu_118_V_data_V_data_2_din;

assign V_data_V_data_3_din = grp_getVoltages_fu_118_V_data_V_data_3_din;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call33 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = ((simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_rowEnd_V_out_full_n == 1'b0) | (simConfig_rowBegin_V_out_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_getVoltages_fu_118_ap_start = grp_getVoltages_fu_118_ap_start_reg;

assign simConfig_BLOCK_NUMBERS_V_out_din = p_read3;

assign simConfig_rowBegin_V_out_din = p_read;

assign simConfig_rowEnd_V_out_din = p_read1;

assign simConfig_rowsToSimulate_V_out_din = p_read2;

assign start_out = real_start;

endmodule //blockControl173
