// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module acc (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        simConfig_rowsToSimulate_V_dout,
        simConfig_rowsToSimulate_V_empty_n,
        simConfig_rowsToSimulate_V_read,
        simConfig_BLOCK_NUMBERS_V_dout,
        simConfig_BLOCK_NUMBERS_V_empty_n,
        simConfig_BLOCK_NUMBERS_V_read,
        simConfig_rowsToSimulate_V_out_din,
        simConfig_rowsToSimulate_V_out_full_n,
        simConfig_rowsToSimulate_V_out_write,
        simConfig_BLOCK_NUMBERS_V_out_din,
        simConfig_BLOCK_NUMBERS_V_out_full_n,
        simConfig_BLOCK_NUMBERS_V_out_write,
        F_V_data_0_dout,
        F_V_data_0_empty_n,
        F_V_data_0_read,
        F_V_data_1_dout,
        F_V_data_1_empty_n,
        F_V_data_1_read,
        F_V_data_2_dout,
        F_V_data_2_empty_n,
        F_V_data_2_read,
        F_V_data_3_dout,
        F_V_data_3_empty_n,
        F_V_data_3_read,
        V_V_data_0_dout,
        V_V_data_0_empty_n,
        V_V_data_0_read,
        V_V_data_1_dout,
        V_V_data_1_empty_n,
        V_V_data_1_read,
        V_V_data_2_dout,
        V_V_data_2_empty_n,
        V_V_data_2_read,
        V_V_data_3_dout,
        V_V_data_3_empty_n,
        V_V_data_3_read,
        F_acc_V_data_0_din,
        F_acc_V_data_0_full_n,
        F_acc_V_data_0_write,
        F_acc_V_data_1_din,
        F_acc_V_data_1_full_n,
        F_acc_V_data_1_write,
        F_acc_V_data_2_din,
        F_acc_V_data_2_full_n,
        F_acc_V_data_2_write,
        F_acc_V_data_3_din,
        F_acc_V_data_3_full_n,
        F_acc_V_data_3_write,
        V_acc_V_data_0_din,
        V_acc_V_data_0_full_n,
        V_acc_V_data_0_write,
        V_acc_V_data_1_din,
        V_acc_V_data_1_full_n,
        V_acc_V_data_1_write,
        V_acc_V_data_2_din,
        V_acc_V_data_2_full_n,
        V_acc_V_data_2_write,
        V_acc_V_data_3_din,
        V_acc_V_data_3_full_n,
        V_acc_V_data_3_write
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_pp0_stage0 = 16'd128;
parameter    ap_ST_fsm_pp0_stage1 = 16'd256;
parameter    ap_ST_fsm_pp0_stage2 = 16'd512;
parameter    ap_ST_fsm_pp0_stage3 = 16'd1024;
parameter    ap_ST_fsm_pp0_stage4 = 16'd2048;
parameter    ap_ST_fsm_pp0_stage5 = 16'd4096;
parameter    ap_ST_fsm_pp0_stage6 = 16'd8192;
parameter    ap_ST_fsm_pp0_stage7 = 16'd16384;
parameter    ap_ST_fsm_state34 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [26:0] simConfig_rowsToSimulate_V_dout;
input   simConfig_rowsToSimulate_V_empty_n;
output   simConfig_rowsToSimulate_V_read;
input  [26:0] simConfig_BLOCK_NUMBERS_V_dout;
input   simConfig_BLOCK_NUMBERS_V_empty_n;
output   simConfig_BLOCK_NUMBERS_V_read;
output  [26:0] simConfig_rowsToSimulate_V_out_din;
input   simConfig_rowsToSimulate_V_out_full_n;
output   simConfig_rowsToSimulate_V_out_write;
output  [26:0] simConfig_BLOCK_NUMBERS_V_out_din;
input   simConfig_BLOCK_NUMBERS_V_out_full_n;
output   simConfig_BLOCK_NUMBERS_V_out_write;
input  [31:0] F_V_data_0_dout;
input   F_V_data_0_empty_n;
output   F_V_data_0_read;
input  [31:0] F_V_data_1_dout;
input   F_V_data_1_empty_n;
output   F_V_data_1_read;
input  [31:0] F_V_data_2_dout;
input   F_V_data_2_empty_n;
output   F_V_data_2_read;
input  [31:0] F_V_data_3_dout;
input   F_V_data_3_empty_n;
output   F_V_data_3_read;
input  [31:0] V_V_data_0_dout;
input   V_V_data_0_empty_n;
output   V_V_data_0_read;
input  [31:0] V_V_data_1_dout;
input   V_V_data_1_empty_n;
output   V_V_data_1_read;
input  [31:0] V_V_data_2_dout;
input   V_V_data_2_empty_n;
output   V_V_data_2_read;
input  [31:0] V_V_data_3_dout;
input   V_V_data_3_empty_n;
output   V_V_data_3_read;
output  [31:0] F_acc_V_data_0_din;
input   F_acc_V_data_0_full_n;
output   F_acc_V_data_0_write;
output  [31:0] F_acc_V_data_1_din;
input   F_acc_V_data_1_full_n;
output   F_acc_V_data_1_write;
output  [31:0] F_acc_V_data_2_din;
input   F_acc_V_data_2_full_n;
output   F_acc_V_data_2_write;
output  [31:0] F_acc_V_data_3_din;
input   F_acc_V_data_3_full_n;
output   F_acc_V_data_3_write;
output  [31:0] V_acc_V_data_0_din;
input   V_acc_V_data_0_full_n;
output   V_acc_V_data_0_write;
output  [31:0] V_acc_V_data_1_din;
input   V_acc_V_data_1_full_n;
output   V_acc_V_data_1_write;
output  [31:0] V_acc_V_data_2_din;
input   V_acc_V_data_2_full_n;
output   V_acc_V_data_2_write;
output  [31:0] V_acc_V_data_3_din;
input   V_acc_V_data_3_full_n;
output   V_acc_V_data_3_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg simConfig_rowsToSimulate_V_read;
reg simConfig_BLOCK_NUMBERS_V_read;
reg simConfig_rowsToSimulate_V_out_write;
reg simConfig_BLOCK_NUMBERS_V_out_write;
reg F_V_data_0_read;
reg F_V_data_1_read;
reg F_V_data_2_read;
reg F_V_data_3_read;
reg V_V_data_0_read;
reg V_V_data_1_read;
reg V_V_data_2_read;
reg V_V_data_3_read;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    simConfig_rowsToSimulate_V_blk_n;
reg    simConfig_BLOCK_NUMBERS_V_blk_n;
reg    simConfig_rowsToSimulate_V_out_blk_n;
reg    simConfig_BLOCK_NUMBERS_V_out_blk_n;
wire    grp_readCalcData_fu_159_F_V_data_0_blk_n;
reg    F_V_data_0_blk_n;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1;
reg   [0:0] exitcond_flatten_reg_263;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
wire    grp_readCalcData_fu_159_F_V_data_1_blk_n;
reg    F_V_data_1_blk_n;
wire    grp_readCalcData_fu_159_F_V_data_2_blk_n;
reg    F_V_data_2_blk_n;
wire    grp_readCalcData_fu_159_F_V_data_3_blk_n;
reg    F_V_data_3_blk_n;
wire    grp_readCalcData_fu_159_V_V_data_0_blk_n;
reg    V_V_data_0_blk_n;
wire    grp_readCalcData_fu_159_V_V_data_1_blk_n;
reg    V_V_data_1_blk_n;
wire    grp_readCalcData_fu_159_V_V_data_2_blk_n;
reg    V_V_data_2_blk_n;
wire    grp_readCalcData_fu_159_V_V_data_3_blk_n;
reg    V_V_data_3_blk_n;
reg    F_acc_V_data_0_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] exitcond_flatten_reg_263_pp0_iter3_reg;
reg    F_acc_V_data_1_blk_n;
reg    F_acc_V_data_2_blk_n;
reg    F_acc_V_data_3_blk_n;
reg    V_acc_V_data_0_blk_n;
reg    V_acc_V_data_1_blk_n;
reg    V_acc_V_data_2_blk_n;
reg    V_acc_V_data_3_blk_n;
reg   [53:0] indvar_flatten_reg_148;
reg    ap_block_state1;
wire   [53:0] grp_fu_231_p2;
reg   [53:0] bound_reg_258;
wire    ap_CS_fsm_state7;
wire   [0:0] exitcond_flatten_fu_237_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state8_pp0_stage0_iter0;
wire    ap_block_state16_pp0_stage0_iter1;
wire    ap_block_state24_pp0_stage0_iter2;
wire    ap_block_state32_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond_flatten_reg_263_pp0_iter1_reg;
reg   [0:0] exitcond_flatten_reg_263_pp0_iter2_reg;
wire   [53:0] indvar_flatten_next_fu_242_p2;
reg   [53:0] indvar_flatten_next_reg_267;
reg   [31:0] F_vector_data_0_reg_272;
reg    ap_block_state9_pp0_stage1_iter0;
wire    ap_block_state17_pp0_stage1_iter1;
wire    ap_block_state25_pp0_stage1_iter2;
wire    F_acc_V_data_01_status;
wire    V_acc_V_data_01_status;
reg    ap_block_state33_pp0_stage1_iter3;
reg    ap_block_pp0_stage1_11001;
reg   [31:0] F_vector_data_1_reg_277;
reg   [31:0] F_vector_data_2_reg_282;
reg   [31:0] F_vector_data_3_reg_287;
reg   [31:0] V_vector_data_0_reg_292;
reg   [31:0] V_vector_data_1_reg_297;
reg   [31:0] V_vector_data_2_reg_302;
reg   [31:0] V_vector_data_3_reg_307;
reg   [31:0] F_vector_data_0_1_reg_312;
reg    ap_block_state10_pp0_stage2_iter0;
wire    ap_block_state18_pp0_stage2_iter1;
wire    ap_block_state26_pp0_stage2_iter2;
reg    ap_block_pp0_stage2_11001;
reg   [31:0] F_vector_data_1_1_reg_317;
reg   [31:0] F_vector_data_2_1_reg_322;
reg   [31:0] F_vector_data_3_1_reg_327;
reg   [31:0] V_vector_data_0_1_reg_332;
reg   [31:0] V_vector_data_1_1_reg_337;
reg   [31:0] V_vector_data_2_1_reg_342;
reg   [31:0] V_vector_data_3_1_reg_347;
reg   [31:0] F_vector_data_0_2_reg_352;
reg    ap_block_state11_pp0_stage3_iter0;
wire    ap_block_state19_pp0_stage3_iter1;
wire    ap_block_state27_pp0_stage3_iter2;
reg    ap_block_pp0_stage3_11001;
reg   [31:0] F_vector_data_1_2_reg_357;
reg   [31:0] F_vector_data_2_2_reg_362;
reg   [31:0] F_vector_data_3_2_reg_367;
reg   [31:0] V_vector_data_0_2_reg_372;
reg   [31:0] V_vector_data_1_2_reg_377;
reg   [31:0] V_vector_data_2_2_reg_382;
reg   [31:0] V_vector_data_3_2_reg_387;
reg   [31:0] F_vector_data_0_3_reg_392;
reg    ap_block_state12_pp0_stage4_iter0;
wire    ap_block_state20_pp0_stage4_iter1;
wire    ap_block_state28_pp0_stage4_iter2;
reg    ap_block_pp0_stage4_11001;
reg   [31:0] F_vector_data_1_3_reg_397;
reg   [31:0] F_vector_data_2_3_reg_402;
reg   [31:0] F_vector_data_3_3_reg_407;
reg   [31:0] V_vector_data_0_3_reg_412;
reg   [31:0] V_vector_data_1_3_reg_417;
reg   [31:0] V_vector_data_2_3_reg_422;
reg   [31:0] V_vector_data_3_3_reg_427;
wire   [31:0] grp_fu_179_p2;
reg   [31:0] dataTemp1_reg_432;
reg    ap_enable_reg_pp0_iter1;
wire   [31:0] grp_fu_183_p2;
reg   [31:0] dataTemp2_reg_437;
wire   [31:0] grp_fu_187_p2;
reg   [31:0] dataTemp1_1_reg_442;
reg   [31:0] dataTemp2_1_reg_447;
reg   [31:0] dataTemp1_2_reg_452;
reg   [31:0] dataTemp2_2_reg_457;
reg   [31:0] dataTemp1_3_reg_462;
reg   [31:0] dataTemp2_3_reg_467;
reg   [31:0] dataTemp1_4_reg_472;
reg   [31:0] dataTemp2_4_reg_477;
reg   [31:0] dataTemp1_5_reg_482;
reg   [31:0] dataTemp2_5_reg_487;
reg   [31:0] dataTemp1_6_reg_492;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state13_pp0_stage5_iter0;
wire    ap_block_state21_pp0_stage5_iter1;
wire    ap_block_state29_pp0_stage5_iter2;
wire    ap_block_pp0_stage5_11001;
reg   [31:0] dataTemp2_6_reg_497;
reg   [31:0] dataTemp1_7_reg_502;
reg   [31:0] dataTemp2_7_reg_507;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state14_pp0_stage6_iter0;
wire    ap_block_state22_pp0_stage6_iter1;
wire    ap_block_state30_pp0_stage6_iter2;
wire    ap_block_pp0_stage6_11001;
reg   [31:0] tmp_data_0_reg_512;
reg    ap_enable_reg_pp0_iter2;
reg   [31:0] tmp_data_0_4_reg_517;
reg   [31:0] tmp_data_1_reg_522;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state15_pp0_stage7_iter0;
wire    ap_block_state23_pp0_stage7_iter1;
wire    ap_block_state31_pp0_stage7_iter2;
wire    ap_block_pp0_stage7_11001;
reg   [31:0] tmp_data_1_4_reg_527;
reg   [31:0] tmp_data_2_reg_532;
reg   [31:0] tmp_data_2_4_reg_537;
reg   [31:0] tmp_data_3_reg_542;
reg   [31:0] tmp_data_3_4_reg_547;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state8;
wire    ap_block_pp0_stage7_subdone;
reg    ap_block_pp0_stage1_subdone;
wire    grp_readCalcData_fu_159_ap_start;
wire    grp_readCalcData_fu_159_ap_done;
wire    grp_readCalcData_fu_159_ap_idle;
wire    grp_readCalcData_fu_159_ap_ready;
wire    grp_readCalcData_fu_159_F_V_data_0_read;
wire    grp_readCalcData_fu_159_F_V_data_1_read;
wire    grp_readCalcData_fu_159_F_V_data_2_read;
wire    grp_readCalcData_fu_159_F_V_data_3_read;
wire    grp_readCalcData_fu_159_V_V_data_0_read;
wire    grp_readCalcData_fu_159_V_V_data_1_read;
wire    grp_readCalcData_fu_159_V_V_data_2_read;
wire    grp_readCalcData_fu_159_V_V_data_3_read;
wire   [31:0] grp_readCalcData_fu_159_ap_return_0;
wire   [31:0] grp_readCalcData_fu_159_ap_return_1;
wire   [31:0] grp_readCalcData_fu_159_ap_return_2;
wire   [31:0] grp_readCalcData_fu_159_ap_return_3;
wire   [31:0] grp_readCalcData_fu_159_ap_return_4;
wire   [31:0] grp_readCalcData_fu_159_ap_return_5;
wire   [31:0] grp_readCalcData_fu_159_ap_return_6;
wire   [31:0] grp_readCalcData_fu_159_ap_return_7;
reg    grp_readCalcData_fu_159_ap_ce;
wire    ap_block_state9_pp0_stage1_iter0_ignore_call3;
wire    ap_block_state17_pp0_stage1_iter1_ignore_call3;
wire    ap_block_state25_pp0_stage1_iter2_ignore_call3;
reg    ap_block_state33_pp0_stage1_iter3_ignore_call3;
reg    ap_block_pp0_stage1_11001_ignoreCallOp89;
wire    ap_block_state10_pp0_stage2_iter0_ignore_call18;
wire    ap_block_state18_pp0_stage2_iter1_ignore_call18;
wire    ap_block_state26_pp0_stage2_iter2_ignore_call18;
wire    ap_block_pp0_stage2_11001_ignoreCallOp101;
wire    ap_block_state11_pp0_stage3_iter0_ignore_call33;
wire    ap_block_state19_pp0_stage3_iter1_ignore_call33;
wire    ap_block_state27_pp0_stage3_iter2_ignore_call33;
wire    ap_block_pp0_stage3_11001_ignoreCallOp116;
wire    ap_block_state12_pp0_stage4_iter0_ignore_call48;
wire    ap_block_state20_pp0_stage4_iter1_ignore_call48;
wire    ap_block_state28_pp0_stage4_iter2_ignore_call48;
wire    ap_block_pp0_stage4_11001_ignoreCallOp134;
reg   [53:0] ap_phi_mux_indvar_flatten_phi_fu_152_p4;
wire    ap_block_pp0_stage0;
reg    grp_readCalcData_fu_159_ap_start_reg;
reg    F_acc_V_data_01_update;
reg    ap_block_pp0_stage1_01001;
reg    V_acc_V_data_01_update;
reg   [31:0] grp_fu_179_p0;
reg   [31:0] grp_fu_179_p1;
wire    ap_block_pp0_stage5;
wire    ap_block_pp0_stage6;
wire    ap_block_pp0_stage7;
reg   [31:0] grp_fu_183_p0;
reg   [31:0] grp_fu_183_p1;
reg   [31:0] grp_fu_187_p0;
reg   [31:0] grp_fu_187_p1;
wire   [26:0] grp_fu_231_p0;
wire   [26:0] grp_fu_231_p1;
reg    grp_fu_179_ce;
reg    grp_fu_183_ce;
reg    grp_fu_187_ce;
reg    grp_fu_231_ce;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state34;
reg   [15:0] ap_NS_fsm;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [53:0] grp_fu_231_p00;
wire   [53:0] grp_fu_231_p10;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 16'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 grp_readCalcData_fu_159_ap_start_reg = 1'b0;
end

readCalcData grp_readCalcData_fu_159(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_readCalcData_fu_159_ap_start),
    .ap_done(grp_readCalcData_fu_159_ap_done),
    .ap_idle(grp_readCalcData_fu_159_ap_idle),
    .ap_ready(grp_readCalcData_fu_159_ap_ready),
    .F_V_data_0_dout(F_V_data_0_dout),
    .F_V_data_0_empty_n(F_V_data_0_empty_n),
    .F_V_data_0_read(grp_readCalcData_fu_159_F_V_data_0_read),
    .F_V_data_1_dout(F_V_data_1_dout),
    .F_V_data_1_empty_n(F_V_data_1_empty_n),
    .F_V_data_1_read(grp_readCalcData_fu_159_F_V_data_1_read),
    .F_V_data_2_dout(F_V_data_2_dout),
    .F_V_data_2_empty_n(F_V_data_2_empty_n),
    .F_V_data_2_read(grp_readCalcData_fu_159_F_V_data_2_read),
    .F_V_data_3_dout(F_V_data_3_dout),
    .F_V_data_3_empty_n(F_V_data_3_empty_n),
    .F_V_data_3_read(grp_readCalcData_fu_159_F_V_data_3_read),
    .V_V_data_0_dout(V_V_data_0_dout),
    .V_V_data_0_empty_n(V_V_data_0_empty_n),
    .V_V_data_0_read(grp_readCalcData_fu_159_V_V_data_0_read),
    .V_V_data_1_dout(V_V_data_1_dout),
    .V_V_data_1_empty_n(V_V_data_1_empty_n),
    .V_V_data_1_read(grp_readCalcData_fu_159_V_V_data_1_read),
    .V_V_data_2_dout(V_V_data_2_dout),
    .V_V_data_2_empty_n(V_V_data_2_empty_n),
    .V_V_data_2_read(grp_readCalcData_fu_159_V_V_data_2_read),
    .V_V_data_3_dout(V_V_data_3_dout),
    .V_V_data_3_empty_n(V_V_data_3_empty_n),
    .V_V_data_3_read(grp_readCalcData_fu_159_V_V_data_3_read),
    .ap_return_0(grp_readCalcData_fu_159_ap_return_0),
    .ap_return_1(grp_readCalcData_fu_159_ap_return_1),
    .ap_return_2(grp_readCalcData_fu_159_ap_return_2),
    .ap_return_3(grp_readCalcData_fu_159_ap_return_3),
    .ap_return_4(grp_readCalcData_fu_159_ap_return_4),
    .ap_return_5(grp_readCalcData_fu_159_ap_return_5),
    .ap_return_6(grp_readCalcData_fu_159_ap_return_6),
    .ap_return_7(grp_readCalcData_fu_159_ap_return_7),
    .F_V_data_0_blk_n(grp_readCalcData_fu_159_F_V_data_0_blk_n),
    .F_V_data_1_blk_n(grp_readCalcData_fu_159_F_V_data_1_blk_n),
    .F_V_data_2_blk_n(grp_readCalcData_fu_159_F_V_data_2_blk_n),
    .F_V_data_3_blk_n(grp_readCalcData_fu_159_F_V_data_3_blk_n),
    .V_V_data_0_blk_n(grp_readCalcData_fu_159_V_V_data_0_blk_n),
    .V_V_data_1_blk_n(grp_readCalcData_fu_159_V_V_data_1_blk_n),
    .V_V_data_2_blk_n(grp_readCalcData_fu_159_V_V_data_2_blk_n),
    .V_V_data_3_blk_n(grp_readCalcData_fu_159_V_V_data_3_blk_n),
    .ap_ce(grp_readCalcData_fu_159_ap_ce)
);

GapJunctionIP_fadd_32ns_32ns_32_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
GapJunctionIP_fadd_32ns_32ns_32_8_full_dsp_1_U139(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_179_p0),
    .din1(grp_fu_179_p1),
    .ce(grp_fu_179_ce),
    .dout(grp_fu_179_p2)
);

GapJunctionIP_fadd_32ns_32ns_32_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
GapJunctionIP_fadd_32ns_32ns_32_8_full_dsp_1_U140(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_183_p0),
    .din1(grp_fu_183_p1),
    .ce(grp_fu_183_ce),
    .dout(grp_fu_183_p2)
);

GapJunctionIP_fadd_32ns_32ns_32_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
GapJunctionIP_fadd_32ns_32ns_32_8_full_dsp_1_U141(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_187_p0),
    .din1(grp_fu_187_p1),
    .ce(grp_fu_187_ce),
    .dout(grp_fu_187_p2)
);

GapJunctionIP_mul_27ns_27ns_54_7_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 27 ),
    .din1_WIDTH( 27 ),
    .dout_WIDTH( 54 ))
GapJunctionIP_mul_27ns_27ns_54_7_1_U142(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_231_p0),
    .din1(grp_fu_231_p1),
    .ce(grp_fu_231_ce),
    .dout(grp_fu_231_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state34)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state8) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_readCalcData_fu_159_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_fu_237_p2 == 1'd0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0)))) begin
            grp_readCalcData_fu_159_ap_start_reg <= 1'b1;
        end else if ((grp_readCalcData_fu_159_ap_ready == 1'b1)) begin
            grp_readCalcData_fu_159_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_263 == 1'd0))) begin
        indvar_flatten_reg_148 <= indvar_flatten_next_reg_267;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        indvar_flatten_reg_148 <= 54'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_reg_263 == 1'd0))) begin
        F_vector_data_0_1_reg_312 <= grp_readCalcData_fu_159_ap_return_0;
        F_vector_data_1_1_reg_317 <= grp_readCalcData_fu_159_ap_return_1;
        F_vector_data_2_1_reg_322 <= grp_readCalcData_fu_159_ap_return_2;
        F_vector_data_3_1_reg_327 <= grp_readCalcData_fu_159_ap_return_3;
        V_vector_data_0_1_reg_332 <= grp_readCalcData_fu_159_ap_return_4;
        V_vector_data_1_1_reg_337 <= grp_readCalcData_fu_159_ap_return_5;
        V_vector_data_2_1_reg_342 <= grp_readCalcData_fu_159_ap_return_6;
        V_vector_data_3_1_reg_347 <= grp_readCalcData_fu_159_ap_return_7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_reg_263 == 1'd0))) begin
        F_vector_data_0_2_reg_352 <= grp_readCalcData_fu_159_ap_return_0;
        F_vector_data_1_2_reg_357 <= grp_readCalcData_fu_159_ap_return_1;
        F_vector_data_2_2_reg_362 <= grp_readCalcData_fu_159_ap_return_2;
        F_vector_data_3_2_reg_367 <= grp_readCalcData_fu_159_ap_return_3;
        V_vector_data_0_2_reg_372 <= grp_readCalcData_fu_159_ap_return_4;
        V_vector_data_1_2_reg_377 <= grp_readCalcData_fu_159_ap_return_5;
        V_vector_data_2_2_reg_382 <= grp_readCalcData_fu_159_ap_return_6;
        V_vector_data_3_2_reg_387 <= grp_readCalcData_fu_159_ap_return_7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_reg_263 == 1'd0))) begin
        F_vector_data_0_3_reg_392 <= grp_readCalcData_fu_159_ap_return_0;
        F_vector_data_1_3_reg_397 <= grp_readCalcData_fu_159_ap_return_1;
        F_vector_data_2_3_reg_402 <= grp_readCalcData_fu_159_ap_return_2;
        F_vector_data_3_3_reg_407 <= grp_readCalcData_fu_159_ap_return_3;
        V_vector_data_0_3_reg_412 <= grp_readCalcData_fu_159_ap_return_4;
        V_vector_data_1_3_reg_417 <= grp_readCalcData_fu_159_ap_return_5;
        V_vector_data_2_3_reg_422 <= grp_readCalcData_fu_159_ap_return_6;
        V_vector_data_3_3_reg_427 <= grp_readCalcData_fu_159_ap_return_7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0))) begin
        F_vector_data_0_reg_272 <= grp_readCalcData_fu_159_ap_return_0;
        F_vector_data_1_reg_277 <= grp_readCalcData_fu_159_ap_return_1;
        F_vector_data_2_reg_282 <= grp_readCalcData_fu_159_ap_return_2;
        F_vector_data_3_reg_287 <= grp_readCalcData_fu_159_ap_return_3;
        V_vector_data_0_reg_292 <= grp_readCalcData_fu_159_ap_return_4;
        V_vector_data_1_reg_297 <= grp_readCalcData_fu_159_ap_return_5;
        V_vector_data_2_reg_302 <= grp_readCalcData_fu_159_ap_return_6;
        V_vector_data_3_reg_307 <= grp_readCalcData_fu_159_ap_return_7;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        bound_reg_258 <= grp_fu_231_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263_pp0_iter1_reg == 1'd0))) begin
        dataTemp1_1_reg_442 <= grp_fu_187_p2;
        dataTemp1_reg_432 <= grp_fu_179_p2;
        dataTemp2_reg_437 <= grp_fu_183_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (exitcond_flatten_reg_263_pp0_iter1_reg == 1'd0))) begin
        dataTemp1_2_reg_452 <= grp_fu_183_p2;
        dataTemp2_1_reg_447 <= grp_fu_179_p2;
        dataTemp2_2_reg_457 <= grp_fu_187_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (exitcond_flatten_reg_263_pp0_iter1_reg == 1'd0))) begin
        dataTemp1_3_reg_462 <= grp_fu_179_p2;
        dataTemp1_4_reg_472 <= grp_fu_187_p2;
        dataTemp2_3_reg_467 <= grp_fu_183_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (exitcond_flatten_reg_263_pp0_iter1_reg == 1'd0))) begin
        dataTemp1_5_reg_482 <= grp_fu_183_p2;
        dataTemp2_4_reg_477 <= grp_fu_179_p2;
        dataTemp2_5_reg_487 <= grp_fu_187_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (exitcond_flatten_reg_263_pp0_iter1_reg == 1'd0))) begin
        dataTemp1_6_reg_492 <= grp_fu_179_p2;
        dataTemp1_7_reg_502 <= grp_fu_187_p2;
        dataTemp2_6_reg_497 <= grp_fu_183_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (exitcond_flatten_reg_263_pp0_iter1_reg == 1'd0))) begin
        dataTemp2_7_reg_507 <= grp_fu_179_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond_flatten_reg_263 <= exitcond_flatten_fu_237_p2;
        exitcond_flatten_reg_263_pp0_iter1_reg <= exitcond_flatten_reg_263;
        exitcond_flatten_reg_263_pp0_iter2_reg <= exitcond_flatten_reg_263_pp0_iter1_reg;
        exitcond_flatten_reg_263_pp0_iter3_reg <= exitcond_flatten_reg_263_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        indvar_flatten_next_reg_267 <= indvar_flatten_next_fu_242_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (exitcond_flatten_reg_263_pp0_iter2_reg == 1'd0))) begin
        tmp_data_0_4_reg_517 <= grp_fu_187_p2;
        tmp_data_0_reg_512 <= grp_fu_183_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter2 == 1'b1) & (exitcond_flatten_reg_263_pp0_iter2_reg == 1'd0))) begin
        tmp_data_1_4_reg_527 <= grp_fu_183_p2;
        tmp_data_1_reg_522 <= grp_fu_179_p2;
        tmp_data_2_reg_532 <= grp_fu_187_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (exitcond_flatten_reg_263_pp0_iter2_reg == 1'd0))) begin
        tmp_data_2_4_reg_537 <= grp_fu_179_p2;
        tmp_data_3_4_reg_547 <= grp_fu_187_p2;
        tmp_data_3_reg_542 <= grp_fu_183_p2;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        F_V_data_0_blk_n = grp_readCalcData_fu_159_F_V_data_0_blk_n;
    end else begin
        F_V_data_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        F_V_data_0_read = grp_readCalcData_fu_159_F_V_data_0_read;
    end else begin
        F_V_data_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        F_V_data_1_blk_n = grp_readCalcData_fu_159_F_V_data_1_blk_n;
    end else begin
        F_V_data_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        F_V_data_1_read = grp_readCalcData_fu_159_F_V_data_1_read;
    end else begin
        F_V_data_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        F_V_data_2_blk_n = grp_readCalcData_fu_159_F_V_data_2_blk_n;
    end else begin
        F_V_data_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        F_V_data_2_read = grp_readCalcData_fu_159_F_V_data_2_read;
    end else begin
        F_V_data_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        F_V_data_3_blk_n = grp_readCalcData_fu_159_F_V_data_3_blk_n;
    end else begin
        F_V_data_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        F_V_data_3_read = grp_readCalcData_fu_159_F_V_data_3_read;
    end else begin
        F_V_data_3_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0))) begin
        F_acc_V_data_01_update = 1'b1;
    end else begin
        F_acc_V_data_01_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1))) begin
        F_acc_V_data_0_blk_n = F_acc_V_data_0_full_n;
    end else begin
        F_acc_V_data_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1))) begin
        F_acc_V_data_1_blk_n = F_acc_V_data_1_full_n;
    end else begin
        F_acc_V_data_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1))) begin
        F_acc_V_data_2_blk_n = F_acc_V_data_2_full_n;
    end else begin
        F_acc_V_data_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1))) begin
        F_acc_V_data_3_blk_n = F_acc_V_data_3_full_n;
    end else begin
        F_acc_V_data_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        V_V_data_0_blk_n = grp_readCalcData_fu_159_V_V_data_0_blk_n;
    end else begin
        V_V_data_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        V_V_data_0_read = grp_readCalcData_fu_159_V_V_data_0_read;
    end else begin
        V_V_data_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        V_V_data_1_blk_n = grp_readCalcData_fu_159_V_V_data_1_blk_n;
    end else begin
        V_V_data_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        V_V_data_1_read = grp_readCalcData_fu_159_V_V_data_1_read;
    end else begin
        V_V_data_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        V_V_data_2_blk_n = grp_readCalcData_fu_159_V_V_data_2_blk_n;
    end else begin
        V_V_data_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        V_V_data_2_read = grp_readCalcData_fu_159_V_V_data_2_read;
    end else begin
        V_V_data_2_read = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        V_V_data_3_blk_n = grp_readCalcData_fu_159_V_V_data_3_blk_n;
    end else begin
        V_V_data_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (exitcond_flatten_reg_263 == 1'd0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (exitcond_flatten_reg_263 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263 == 1'd0) & (1'b0 == ap_block_pp0_stage1)))) begin
        V_V_data_3_read = grp_readCalcData_fu_159_V_V_data_3_read;
    end else begin
        V_V_data_3_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0))) begin
        V_acc_V_data_01_update = 1'b1;
    end else begin
        V_acc_V_data_01_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1))) begin
        V_acc_V_data_0_blk_n = V_acc_V_data_0_full_n;
    end else begin
        V_acc_V_data_0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1))) begin
        V_acc_V_data_1_blk_n = V_acc_V_data_1_full_n;
    end else begin
        V_acc_V_data_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1))) begin
        V_acc_V_data_2_blk_n = V_acc_V_data_2_full_n;
    end else begin
        V_acc_V_data_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1))) begin
        V_acc_V_data_3_blk_n = V_acc_V_data_3_full_n;
    end else begin
        V_acc_V_data_3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_237_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state8 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state8 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_263 == 1'd0))) begin
        ap_phi_mux_indvar_flatten_phi_fu_152_p4 = indvar_flatten_next_reg_267;
    end else begin
        ap_phi_mux_indvar_flatten_phi_fu_152_p4 = indvar_flatten_reg_148;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_179_ce = 1'b1;
    end else begin
        grp_fu_179_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_179_p0 = dataTemp1_5_reg_482;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_179_p0 = dataTemp1_2_reg_452;
    end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_179_p0 = V_vector_data_2_3_reg_422;
    end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_179_p0 = F_vector_data_0_3_reg_392;
    end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_179_p0 = F_vector_data_2_2_reg_362;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4))) begin
        grp_fu_179_p0 = V_vector_data_0_1_reg_332;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3))) begin
        grp_fu_179_p0 = V_vector_data_2_reg_302;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2))) begin
        grp_fu_179_p0 = F_vector_data_0_reg_272;
    end else begin
        grp_fu_179_p0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_179_p1 = dataTemp2_5_reg_487;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_179_p1 = dataTemp2_2_reg_457;
    end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_179_p1 = V_vector_data_3_3_reg_427;
    end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_179_p1 = F_vector_data_1_3_reg_397;
    end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_179_p1 = F_vector_data_3_2_reg_367;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4))) begin
        grp_fu_179_p1 = V_vector_data_1_1_reg_337;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3))) begin
        grp_fu_179_p1 = V_vector_data_3_reg_307;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2))) begin
        grp_fu_179_p1 = F_vector_data_1_reg_277;
    end else begin
        grp_fu_179_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_183_ce = 1'b1;
    end else begin
        grp_fu_183_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_183_p0 = dataTemp1_6_reg_492;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_183_p0 = dataTemp1_3_reg_462;
    end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        grp_fu_183_p0 = dataTemp1_reg_432;
    end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_183_p0 = F_vector_data_2_3_reg_402;
    end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_183_p0 = V_vector_data_0_2_reg_372;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4))) begin
        grp_fu_183_p0 = V_vector_data_2_1_reg_342;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3))) begin
        grp_fu_183_p0 = F_vector_data_0_1_reg_312;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2))) begin
        grp_fu_183_p0 = F_vector_data_2_reg_282;
    end else begin
        grp_fu_183_p0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_183_p1 = dataTemp2_6_reg_497;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_183_p1 = dataTemp2_3_reg_467;
    end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        grp_fu_183_p1 = dataTemp2_reg_437;
    end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_183_p1 = F_vector_data_3_3_reg_407;
    end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_183_p1 = V_vector_data_1_2_reg_377;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4))) begin
        grp_fu_183_p1 = V_vector_data_3_1_reg_347;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3))) begin
        grp_fu_183_p1 = F_vector_data_1_1_reg_317;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2))) begin
        grp_fu_183_p1 = F_vector_data_3_reg_287;
    end else begin
        grp_fu_183_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_187_ce = 1'b1;
    end else begin
        grp_fu_187_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_187_p0 = dataTemp1_7_reg_502;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_187_p0 = dataTemp1_4_reg_472;
    end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        grp_fu_187_p0 = dataTemp1_1_reg_442;
    end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_187_p0 = V_vector_data_0_3_reg_412;
    end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_187_p0 = V_vector_data_2_2_reg_382;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4))) begin
        grp_fu_187_p0 = F_vector_data_0_2_reg_352;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3))) begin
        grp_fu_187_p0 = F_vector_data_2_1_reg_322;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2))) begin
        grp_fu_187_p0 = V_vector_data_0_reg_292;
    end else begin
        grp_fu_187_p0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_187_p1 = dataTemp2_7_reg_507;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_187_p1 = dataTemp2_4_reg_477;
    end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        grp_fu_187_p1 = dataTemp2_1_reg_447;
    end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_187_p1 = V_vector_data_1_3_reg_417;
    end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_187_p1 = V_vector_data_3_2_reg_387;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4))) begin
        grp_fu_187_p1 = F_vector_data_1_2_reg_357;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage3))) begin
        grp_fu_187_p1 = F_vector_data_3_1_reg_327;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage2))) begin
        grp_fu_187_p1 = V_vector_data_1_reg_297;
    end else begin
        grp_fu_187_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state7) | (~((ap_done_reg == 1'b1) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_BLOCK_NUMBERS_V_empty_n == 1'b0) | (simConfig_rowsToSimulate_V_empty_n == 1'b0) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_fu_231_ce = 1'b1;
    end else begin
        grp_fu_231_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001_ignoreCallOp134) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp116) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp101) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp89) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_readCalcData_fu_159_ap_ce = 1'b1;
    end else begin
        grp_readCalcData_fu_159_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        simConfig_BLOCK_NUMBERS_V_blk_n = simConfig_BLOCK_NUMBERS_V_empty_n;
    end else begin
        simConfig_BLOCK_NUMBERS_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        simConfig_BLOCK_NUMBERS_V_out_blk_n = simConfig_BLOCK_NUMBERS_V_out_full_n;
    end else begin
        simConfig_BLOCK_NUMBERS_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_BLOCK_NUMBERS_V_empty_n == 1'b0) | (simConfig_rowsToSimulate_V_empty_n == 1'b0) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        simConfig_BLOCK_NUMBERS_V_out_write = 1'b1;
    end else begin
        simConfig_BLOCK_NUMBERS_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_BLOCK_NUMBERS_V_empty_n == 1'b0) | (simConfig_rowsToSimulate_V_empty_n == 1'b0) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        simConfig_BLOCK_NUMBERS_V_read = 1'b1;
    end else begin
        simConfig_BLOCK_NUMBERS_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        simConfig_rowsToSimulate_V_blk_n = simConfig_rowsToSimulate_V_empty_n;
    end else begin
        simConfig_rowsToSimulate_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        simConfig_rowsToSimulate_V_out_blk_n = simConfig_rowsToSimulate_V_out_full_n;
    end else begin
        simConfig_rowsToSimulate_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_BLOCK_NUMBERS_V_empty_n == 1'b0) | (simConfig_rowsToSimulate_V_empty_n == 1'b0) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        simConfig_rowsToSimulate_V_out_write = 1'b1;
    end else begin
        simConfig_rowsToSimulate_V_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_BLOCK_NUMBERS_V_empty_n == 1'b0) | (simConfig_rowsToSimulate_V_empty_n == 1'b0) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        simConfig_rowsToSimulate_V_read = 1'b1;
    end else begin
        simConfig_rowsToSimulate_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_BLOCK_NUMBERS_V_empty_n == 1'b0) | (simConfig_rowsToSimulate_V_empty_n == 1'b0) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond_flatten_fu_237_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond_flatten_fu_237_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F_acc_V_data_01_status = (F_acc_V_data_3_full_n & F_acc_V_data_2_full_n & F_acc_V_data_1_full_n & F_acc_V_data_0_full_n);

assign F_acc_V_data_0_din = tmp_data_0_reg_512;

assign F_acc_V_data_0_write = F_acc_V_data_01_update;

assign F_acc_V_data_1_din = tmp_data_1_reg_522;

assign F_acc_V_data_1_write = F_acc_V_data_01_update;

assign F_acc_V_data_2_din = tmp_data_2_reg_532;

assign F_acc_V_data_2_write = F_acc_V_data_01_update;

assign F_acc_V_data_3_din = tmp_data_3_reg_542;

assign F_acc_V_data_3_write = F_acc_V_data_01_update;

assign V_acc_V_data_01_status = (V_acc_V_data_3_full_n & V_acc_V_data_2_full_n & V_acc_V_data_1_full_n & V_acc_V_data_0_full_n);

assign V_acc_V_data_0_din = tmp_data_0_4_reg_517;

assign V_acc_V_data_0_write = V_acc_V_data_01_update;

assign V_acc_V_data_1_din = tmp_data_1_4_reg_527;

assign V_acc_V_data_1_write = V_acc_V_data_01_update;

assign V_acc_V_data_2_din = tmp_data_2_4_reg_537;

assign V_acc_V_data_2_write = V_acc_V_data_01_update;

assign V_acc_V_data_3_din = tmp_data_3_4_reg_547;

assign V_acc_V_data_3_write = V_acc_V_data_01_update;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (((1'b0 == V_acc_V_data_01_status) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0)) | ((1'b0 == F_acc_V_data_01_status) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0)))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_reg_263 == 1'd0) & ((grp_readCalcData_fu_159_V_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_0_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_0_blk_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (((1'b0 == V_acc_V_data_01_status) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0)) | ((1'b0 == F_acc_V_data_01_status) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0)))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_reg_263 == 1'd0) & ((grp_readCalcData_fu_159_V_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_0_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_0_blk_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_ignoreCallOp89 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (((1'b0 == V_acc_V_data_01_status) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0)) | ((1'b0 == F_acc_V_data_01_status) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0))));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (((1'b0 == V_acc_V_data_01_status) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0)) | ((1'b0 == F_acc_V_data_01_status) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0)))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_reg_263 == 1'd0) & ((grp_readCalcData_fu_159_V_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_0_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_0_blk_n == 1'b0))));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_reg_263 == 1'd0) & ((grp_readCalcData_fu_159_V_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_0_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_0_blk_n == 1'b0)));
end

assign ap_block_pp0_stage2_11001_ignoreCallOp101 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_reg_263 == 1'd0) & ((grp_readCalcData_fu_159_V_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_0_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_0_blk_n == 1'b0)));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_reg_263 == 1'd0) & ((grp_readCalcData_fu_159_V_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_0_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_0_blk_n == 1'b0)));
end

assign ap_block_pp0_stage3_11001_ignoreCallOp116 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_reg_263 == 1'd0) & ((grp_readCalcData_fu_159_V_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_0_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_0_blk_n == 1'b0)));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_reg_263 == 1'd0) & ((grp_readCalcData_fu_159_V_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_0_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_0_blk_n == 1'b0)));
end

assign ap_block_pp0_stage4_11001_ignoreCallOp134 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_reg_263 == 1'd0) & ((grp_readCalcData_fu_159_V_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_0_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_0_blk_n == 1'b0)));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (simConfig_BLOCK_NUMBERS_V_out_full_n == 1'b0) | (simConfig_rowsToSimulate_V_out_full_n == 1'b0) | (simConfig_BLOCK_NUMBERS_V_empty_n == 1'b0) | (simConfig_rowsToSimulate_V_empty_n == 1'b0) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state10_pp0_stage2_iter0 = ((exitcond_flatten_reg_263 == 1'd0) & ((grp_readCalcData_fu_159_V_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_0_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_0_blk_n == 1'b0)));
end

assign ap_block_state10_pp0_stage2_iter0_ignore_call18 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp0_stage3_iter0 = ((exitcond_flatten_reg_263 == 1'd0) & ((grp_readCalcData_fu_159_V_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_0_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_0_blk_n == 1'b0)));
end

assign ap_block_state11_pp0_stage3_iter0_ignore_call33 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_pp0_stage4_iter0 = ((exitcond_flatten_reg_263 == 1'd0) & ((grp_readCalcData_fu_159_V_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_0_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_0_blk_n == 1'b0)));
end

assign ap_block_state12_pp0_stage4_iter0_ignore_call48 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage1_iter1_ignore_call3 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage2_iter1_ignore_call18 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage3_iter1_ignore_call33 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage4_iter1_ignore_call48 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage6_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage7_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage1_iter2_ignore_call3 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage2_iter2_ignore_call18 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage3_iter2_ignore_call33 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage4_iter2_ignore_call48 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage5_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage6_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage7_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state33_pp0_stage1_iter3 = (((1'b0 == V_acc_V_data_01_status) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0)) | ((1'b0 == F_acc_V_data_01_status) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0)));
end

always @ (*) begin
    ap_block_state33_pp0_stage1_iter3_ignore_call3 = (((1'b0 == V_acc_V_data_01_status) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0)) | ((1'b0 == F_acc_V_data_01_status) & (exitcond_flatten_reg_263_pp0_iter3_reg == 1'd0)));
end

assign ap_block_state8_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage1_iter0 = ((exitcond_flatten_reg_263 == 1'd0) & ((grp_readCalcData_fu_159_V_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_V_V_data_0_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_3_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_2_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_1_blk_n == 1'b0) | (grp_readCalcData_fu_159_F_V_data_0_blk_n == 1'b0)));
end

assign ap_block_state9_pp0_stage1_iter0_ignore_call3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign exitcond_flatten_fu_237_p2 = ((ap_phi_mux_indvar_flatten_phi_fu_152_p4 == bound_reg_258) ? 1'b1 : 1'b0);

assign grp_fu_231_p0 = grp_fu_231_p00;

assign grp_fu_231_p00 = simConfig_BLOCK_NUMBERS_V_dout;

assign grp_fu_231_p1 = grp_fu_231_p10;

assign grp_fu_231_p10 = simConfig_rowsToSimulate_V_dout;

assign grp_readCalcData_fu_159_ap_start = grp_readCalcData_fu_159_ap_start_reg;

assign indvar_flatten_next_fu_242_p2 = (ap_phi_mux_indvar_flatten_phi_fu_152_p4 + 54'd1);

assign simConfig_BLOCK_NUMBERS_V_out_din = simConfig_BLOCK_NUMBERS_V_dout;

assign simConfig_rowsToSimulate_V_out_din = simConfig_rowsToSimulate_V_dout;

assign start_out = real_start;

endmodule //acc
