// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _blockControl173_HH_
#define _blockControl173_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "getVoltages.h"

namespace ap_rtl {

struct blockControl173 : public sc_module {
    // Port declarations 42
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<64> > input_V_data_TDATA;
    sc_in< sc_logic > input_V_data_TVALID;
    sc_out< sc_logic > input_V_data_TREADY;
    sc_in< sc_lv<32> > V_SIZE;
    sc_in< sc_lv<27> > p_read;
    sc_in< sc_lv<27> > p_read1;
    sc_in< sc_lv<27> > p_read2;
    sc_in< sc_lv<27> > p_read3;
    sc_out< sc_lv<27> > simConfig_rowBegin_V_out_din;
    sc_in< sc_logic > simConfig_rowBegin_V_out_full_n;
    sc_out< sc_logic > simConfig_rowBegin_V_out_write;
    sc_out< sc_lv<27> > simConfig_rowEnd_V_out_din;
    sc_in< sc_logic > simConfig_rowEnd_V_out_full_n;
    sc_out< sc_logic > simConfig_rowEnd_V_out_write;
    sc_out< sc_lv<27> > simConfig_rowsToSimulate_V_out_din;
    sc_in< sc_logic > simConfig_rowsToSimulate_V_out_full_n;
    sc_out< sc_logic > simConfig_rowsToSimulate_V_out_write;
    sc_out< sc_lv<27> > simConfig_BLOCK_NUMBERS_V_out_din;
    sc_in< sc_logic > simConfig_BLOCK_NUMBERS_V_out_full_n;
    sc_out< sc_logic > simConfig_BLOCK_NUMBERS_V_out_write;
    sc_out< sc_lv<32> > V_data_V_data_0_din;
    sc_in< sc_logic > V_data_V_data_0_full_n;
    sc_out< sc_logic > V_data_V_data_0_write;
    sc_out< sc_lv<32> > V_data_V_data_1_din;
    sc_in< sc_logic > V_data_V_data_1_full_n;
    sc_out< sc_logic > V_data_V_data_1_write;
    sc_out< sc_lv<32> > V_data_V_data_2_din;
    sc_in< sc_logic > V_data_V_data_2_full_n;
    sc_out< sc_logic > V_data_V_data_2_write;
    sc_out< sc_lv<32> > V_data_V_data_3_din;
    sc_in< sc_logic > V_data_V_data_3_full_n;
    sc_out< sc_logic > V_data_V_data_3_write;


    // Module declarations
    blockControl173(sc_module_name name);
    SC_HAS_PROCESS(blockControl173);

    ~blockControl173();

    sc_trace_file* mVcdFile;

    getVoltages* grp_getVoltages_fu_118;
    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > simConfig_rowBegin_V_out_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > simConfig_rowEnd_V_out_blk_n;
    sc_signal< sc_logic > simConfig_rowsToSimulate_V_out_blk_n;
    sc_signal< sc_logic > simConfig_BLOCK_NUMBERS_V_out_blk_n;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_logic > grp_getVoltages_fu_118_ap_start;
    sc_signal< sc_logic > grp_getVoltages_fu_118_ap_done;
    sc_signal< sc_logic > grp_getVoltages_fu_118_ap_idle;
    sc_signal< sc_logic > grp_getVoltages_fu_118_ap_ready;
    sc_signal< sc_logic > grp_getVoltages_fu_118_input_V_data_TREADY;
    sc_signal< sc_lv<32> > grp_getVoltages_fu_118_V_data_V_data_0_din;
    sc_signal< sc_logic > grp_getVoltages_fu_118_V_data_V_data_0_write;
    sc_signal< sc_lv<32> > grp_getVoltages_fu_118_V_data_V_data_1_din;
    sc_signal< sc_logic > grp_getVoltages_fu_118_V_data_V_data_1_write;
    sc_signal< sc_lv<32> > grp_getVoltages_fu_118_V_data_V_data_2_din;
    sc_signal< sc_logic > grp_getVoltages_fu_118_V_data_V_data_2_write;
    sc_signal< sc_lv<32> > grp_getVoltages_fu_118_V_data_V_data_3_din;
    sc_signal< sc_logic > grp_getVoltages_fu_118_V_data_V_data_3_write;
    sc_signal< sc_logic > grp_getVoltages_fu_118_ap_start_reg;
    sc_signal< bool > ap_block_state1_ignore_call33;
    sc_signal< bool > ap_block_state2;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_V_data_V_data_0_din();
    void thread_V_data_V_data_0_write();
    void thread_V_data_V_data_1_din();
    void thread_V_data_V_data_1_write();
    void thread_V_data_V_data_2_din();
    void thread_V_data_V_data_2_write();
    void thread_V_data_V_data_3_din();
    void thread_V_data_V_data_3_write();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_block_state1();
    void thread_ap_block_state1_ignore_call33();
    void thread_ap_block_state2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_grp_getVoltages_fu_118_ap_start();
    void thread_input_V_data_TREADY();
    void thread_internal_ap_ready();
    void thread_real_start();
    void thread_simConfig_BLOCK_NUMBERS_V_out_blk_n();
    void thread_simConfig_BLOCK_NUMBERS_V_out_din();
    void thread_simConfig_BLOCK_NUMBERS_V_out_write();
    void thread_simConfig_rowBegin_V_out_blk_n();
    void thread_simConfig_rowBegin_V_out_din();
    void thread_simConfig_rowBegin_V_out_write();
    void thread_simConfig_rowEnd_V_out_blk_n();
    void thread_simConfig_rowEnd_V_out_din();
    void thread_simConfig_rowEnd_V_out_write();
    void thread_simConfig_rowsToSimulate_V_out_blk_n();
    void thread_simConfig_rowsToSimulate_V_out_din();
    void thread_simConfig_rowsToSimulate_V_out_write();
    void thread_start_out();
    void thread_start_write();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
