// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module execute (
        input_V_data_TDATA,
        output_r_TDATA,
        output_r_TLAST,
        simConfig_rowBegin_V_2,
        simConfig_rowEnd_V_r,
        simConfig_rowsToSimu,
        simConfig_BLOCK_NUMB,
        size,
        ap_clk,
        ap_rst,
        input_V_data_TVALID,
        input_V_data_TREADY,
        size_ap_vld,
        simConfig_rowBegin_V_2_ap_vld,
        simConfig_rowEnd_V_r_ap_vld,
        simConfig_rowsToSimu_ap_vld,
        simConfig_BLOCK_NUMB_ap_vld,
        ap_start,
        output_r_TVALID,
        output_r_TREADY,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [63:0] input_V_data_TDATA;
output  [31:0] output_r_TDATA;
output  [0:0] output_r_TLAST;
input  [26:0] simConfig_rowBegin_V_2;
input  [26:0] simConfig_rowEnd_V_r;
input  [26:0] simConfig_rowsToSimu;
input  [26:0] simConfig_BLOCK_NUMB;
input  [31:0] size;
input   ap_clk;
input   ap_rst;
input   input_V_data_TVALID;
output   input_V_data_TREADY;
input   size_ap_vld;
input   simConfig_rowBegin_V_2_ap_vld;
input   simConfig_rowEnd_V_r_ap_vld;
input   simConfig_rowsToSimu_ap_vld;
input   simConfig_BLOCK_NUMB_ap_vld;
input   ap_start;
output   output_r_TVALID;
input   output_r_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    blockControl173_U0_ap_start;
wire    blockControl173_U0_ap_done;
wire    blockControl173_U0_ap_continue;
wire    blockControl173_U0_ap_idle;
wire    blockControl173_U0_ap_ready;
wire    blockControl173_U0_start_out;
wire    blockControl173_U0_start_write;
wire    blockControl173_U0_input_V_data_TREADY;
wire   [26:0] blockControl173_U0_simConfig_rowBegin_V_out_din;
wire    blockControl173_U0_simConfig_rowBegin_V_out_write;
wire   [26:0] blockControl173_U0_simConfig_rowEnd_V_out_din;
wire    blockControl173_U0_simConfig_rowEnd_V_out_write;
wire   [26:0] blockControl173_U0_simConfig_rowsToSimulate_V_out_din;
wire    blockControl173_U0_simConfig_rowsToSimulate_V_out_write;
wire   [26:0] blockControl173_U0_simConfig_BLOCK_NUMBERS_V_out_din;
wire    blockControl173_U0_simConfig_BLOCK_NUMBERS_V_out_write;
wire   [31:0] blockControl173_U0_V_data_V_data_0_din;
wire    blockControl173_U0_V_data_V_data_0_write;
wire   [31:0] blockControl173_U0_V_data_V_data_1_din;
wire    blockControl173_U0_V_data_V_data_1_write;
wire   [31:0] blockControl173_U0_V_data_V_data_2_din;
wire    blockControl173_U0_V_data_V_data_2_write;
wire   [31:0] blockControl173_U0_V_data_V_data_3_din;
wire    blockControl173_U0_V_data_V_data_3_write;
wire    V_read_U0_ap_start;
wire    V_read_U0_start_out;
wire    V_read_U0_start_write;
wire    V_read_U0_simConfig_rowBegin_V_read;
wire    V_read_U0_simConfig_rowEnd_V_read;
wire    V_read_U0_simConfig_rowsToSimulate_V_read;
wire    V_read_U0_simConfig_BLOCK_NUMBERS_V_read;
wire   [26:0] V_read_U0_simConfig_rowsToSimulate_V_out_din;
wire    V_read_U0_simConfig_rowsToSimulate_V_out_write;
wire   [26:0] V_read_U0_simConfig_BLOCK_NUMBERS_V_out_din;
wire    V_read_U0_simConfig_BLOCK_NUMBERS_V_out_write;
wire    V_read_U0_V_data_V_data_0_read;
wire    V_read_U0_V_data_V_data_1_read;
wire    V_read_U0_V_data_V_data_2_read;
wire    V_read_U0_V_data_V_data_3_read;
wire   [31:0] V_read_U0_fixedData_V_data_din;
wire    V_read_U0_fixedData_V_data_write;
wire   [0:0] V_read_U0_fixedData_V_tlast_V_din;
wire    V_read_U0_fixedData_V_tlast_V_write;
wire   [31:0] V_read_U0_processedData_V_data_din;
wire    V_read_U0_processedData_V_data_write;
wire   [31:0] V_read_U0_processedData_V_data_1_din;
wire    V_read_U0_processedData_V_data_1_write;
wire   [31:0] V_read_U0_processedData_V_data_2_din;
wire    V_read_U0_processedData_V_data_2_write;
wire   [31:0] V_read_U0_processedData_V_data_3_din;
wire    V_read_U0_processedData_V_data_3_write;
wire    V_read_U0_ap_done;
wire    V_read_U0_ap_ready;
wire    V_read_U0_ap_idle;
wire    V_read_U0_ap_continue;
wire    calc_U0_ap_start;
wire    calc_U0_ap_done;
wire    calc_U0_ap_continue;
wire    calc_U0_ap_idle;
wire    calc_U0_ap_ready;
wire    calc_U0_start_out;
wire    calc_U0_start_write;
wire    calc_U0_simConfig_rowsToSimulate_V_read;
wire    calc_U0_simConfig_BLOCK_NUMBERS_V_read;
wire   [26:0] calc_U0_simConfig_rowsToSimulate_V_out_din;
wire    calc_U0_simConfig_rowsToSimulate_V_out_write;
wire   [26:0] calc_U0_simConfig_BLOCK_NUMBERS_V_out_din;
wire    calc_U0_simConfig_BLOCK_NUMBERS_V_out_write;
wire    calc_U0_processedData_V_data_read;
wire    calc_U0_processedData_V_data_1_read;
wire    calc_U0_processedData_V_data_2_read;
wire    calc_U0_processedData_V_data_3_read;
wire    calc_U0_fixedData_V_data_read;
wire    calc_U0_fixedData_V_tlast_V_read;
wire   [31:0] calc_U0_V_V_data_0_din;
wire    calc_U0_V_V_data_0_write;
wire   [31:0] calc_U0_V_V_data_1_din;
wire    calc_U0_V_V_data_1_write;
wire   [31:0] calc_U0_V_V_data_2_din;
wire    calc_U0_V_V_data_2_write;
wire   [31:0] calc_U0_V_V_data_3_din;
wire    calc_U0_V_V_data_3_write;
wire   [31:0] calc_U0_F_V_data_0_din;
wire    calc_U0_F_V_data_0_write;
wire   [31:0] calc_U0_F_V_data_1_din;
wire    calc_U0_F_V_data_1_write;
wire   [31:0] calc_U0_F_V_data_2_din;
wire    calc_U0_F_V_data_2_write;
wire   [31:0] calc_U0_F_V_data_3_din;
wire    calc_U0_F_V_data_3_write;
wire    acc_U0_ap_start;
wire    acc_U0_ap_done;
wire    acc_U0_ap_continue;
wire    acc_U0_ap_idle;
wire    acc_U0_ap_ready;
wire    acc_U0_start_out;
wire    acc_U0_start_write;
wire    acc_U0_simConfig_rowsToSimulate_V_read;
wire    acc_U0_simConfig_BLOCK_NUMBERS_V_read;
wire   [26:0] acc_U0_simConfig_rowsToSimulate_V_out_din;
wire    acc_U0_simConfig_rowsToSimulate_V_out_write;
wire   [26:0] acc_U0_simConfig_BLOCK_NUMBERS_V_out_din;
wire    acc_U0_simConfig_BLOCK_NUMBERS_V_out_write;
wire    acc_U0_F_V_data_0_read;
wire    acc_U0_F_V_data_1_read;
wire    acc_U0_F_V_data_2_read;
wire    acc_U0_F_V_data_3_read;
wire    acc_U0_V_V_data_0_read;
wire    acc_U0_V_V_data_1_read;
wire    acc_U0_V_V_data_2_read;
wire    acc_U0_V_V_data_3_read;
wire   [31:0] acc_U0_F_acc_V_data_0_din;
wire    acc_U0_F_acc_V_data_0_write;
wire   [31:0] acc_U0_F_acc_V_data_1_din;
wire    acc_U0_F_acc_V_data_1_write;
wire   [31:0] acc_U0_F_acc_V_data_2_din;
wire    acc_U0_F_acc_V_data_2_write;
wire   [31:0] acc_U0_F_acc_V_data_3_din;
wire    acc_U0_F_acc_V_data_3_write;
wire   [31:0] acc_U0_V_acc_V_data_0_din;
wire    acc_U0_V_acc_V_data_0_write;
wire   [31:0] acc_U0_V_acc_V_data_1_din;
wire    acc_U0_V_acc_V_data_1_write;
wire   [31:0] acc_U0_V_acc_V_data_2_din;
wire    acc_U0_V_acc_V_data_2_write;
wire   [31:0] acc_U0_V_acc_V_data_3_din;
wire    acc_U0_V_acc_V_data_3_write;
wire    I_calc_U0_ap_start;
wire    I_calc_U0_ap_done;
wire    I_calc_U0_ap_continue;
wire    I_calc_U0_ap_idle;
wire    I_calc_U0_ap_ready;
wire   [31:0] I_calc_U0_output_r_TDATA;
wire    I_calc_U0_output_r_TVALID;
wire   [0:0] I_calc_U0_output_r_TLAST;
wire    I_calc_U0_simConfig_rowsToSimulate_V_read;
wire    I_calc_U0_simConfig_BLOCK_NUMBERS_V_read;
wire    I_calc_U0_F_acc_V_data_0_read;
wire    I_calc_U0_F_acc_V_data_1_read;
wire    I_calc_U0_F_acc_V_data_2_read;
wire    I_calc_U0_F_acc_V_data_3_read;
wire    I_calc_U0_V_acc_V_data_0_read;
wire    I_calc_U0_V_acc_V_data_1_read;
wire    I_calc_U0_V_acc_V_data_2_read;
wire    I_calc_U0_V_acc_V_data_3_read;
wire    ap_sync_continue;
wire    simConfig_rowBegin_V_full_n;
wire   [26:0] simConfig_rowBegin_V_dout;
wire    simConfig_rowBegin_V_empty_n;
wire    simConfig_rowEnd_V_c_full_n;
wire   [26:0] simConfig_rowEnd_V_c_dout;
wire    simConfig_rowEnd_V_c_empty_n;
wire    simConfig_rowsToSimu_4_full_n;
wire   [26:0] simConfig_rowsToSimu_4_dout;
wire    simConfig_rowsToSimu_4_empty_n;
wire    simConfig_BLOCK_NUMB_4_full_n;
wire   [26:0] simConfig_BLOCK_NUMB_4_dout;
wire    simConfig_BLOCK_NUMB_4_empty_n;
wire    V_data_V_data_0_full_n;
wire   [31:0] V_data_V_data_0_dout;
wire    V_data_V_data_0_empty_n;
wire    V_data_V_data_1_full_n;
wire   [31:0] V_data_V_data_1_dout;
wire    V_data_V_data_1_empty_n;
wire    V_data_V_data_2_full_n;
wire   [31:0] V_data_V_data_2_dout;
wire    V_data_V_data_2_empty_n;
wire    V_data_V_data_3_full_n;
wire   [31:0] V_data_V_data_3_dout;
wire    V_data_V_data_3_empty_n;
wire    simConfig_rowsToSimu_3_full_n;
wire   [26:0] simConfig_rowsToSimu_3_dout;
wire    simConfig_rowsToSimu_3_empty_n;
wire    simConfig_BLOCK_NUMB_3_full_n;
wire   [26:0] simConfig_BLOCK_NUMB_3_dout;
wire    simConfig_BLOCK_NUMB_3_empty_n;
wire    fixedData_V_data_full_n;
wire   [31:0] fixedData_V_data_dout;
wire    fixedData_V_data_empty_n;
wire    fixedData_V_tlast_V_full_n;
wire   [0:0] fixedData_V_tlast_V_dout;
wire    fixedData_V_tlast_V_empty_n;
wire    processedData_V_data_full_n;
wire   [31:0] processedData_V_data_dout;
wire    processedData_V_data_empty_n;
wire    processedData_V_data_1_full_n;
wire   [31:0] processedData_V_data_1_dout;
wire    processedData_V_data_1_empty_n;
wire    processedData_V_data_2_full_n;
wire   [31:0] processedData_V_data_2_dout;
wire    processedData_V_data_2_empty_n;
wire    processedData_V_data_3_full_n;
wire   [31:0] processedData_V_data_3_dout;
wire    processedData_V_data_3_empty_n;
wire    simConfig_rowsToSimu_2_full_n;
wire   [26:0] simConfig_rowsToSimu_2_dout;
wire    simConfig_rowsToSimu_2_empty_n;
wire    simConfig_BLOCK_NUMB_2_full_n;
wire   [26:0] simConfig_BLOCK_NUMB_2_dout;
wire    simConfig_BLOCK_NUMB_2_empty_n;
wire    V_V_data_0_full_n;
wire   [31:0] V_V_data_0_dout;
wire    V_V_data_0_empty_n;
wire    V_V_data_1_full_n;
wire   [31:0] V_V_data_1_dout;
wire    V_V_data_1_empty_n;
wire    V_V_data_2_full_n;
wire   [31:0] V_V_data_2_dout;
wire    V_V_data_2_empty_n;
wire    V_V_data_3_full_n;
wire   [31:0] V_V_data_3_dout;
wire    V_V_data_3_empty_n;
wire    F_V_data_0_full_n;
wire   [31:0] F_V_data_0_dout;
wire    F_V_data_0_empty_n;
wire    F_V_data_1_full_n;
wire   [31:0] F_V_data_1_dout;
wire    F_V_data_1_empty_n;
wire    F_V_data_2_full_n;
wire   [31:0] F_V_data_2_dout;
wire    F_V_data_2_empty_n;
wire    F_V_data_3_full_n;
wire   [31:0] F_V_data_3_dout;
wire    F_V_data_3_empty_n;
wire    simConfig_rowsToSimu_1_full_n;
wire   [26:0] simConfig_rowsToSimu_1_dout;
wire    simConfig_rowsToSimu_1_empty_n;
wire    simConfig_BLOCK_NUMB_1_full_n;
wire   [26:0] simConfig_BLOCK_NUMB_1_dout;
wire    simConfig_BLOCK_NUMB_1_empty_n;
wire    F_acc_V_data_0_full_n;
wire   [31:0] F_acc_V_data_0_dout;
wire    F_acc_V_data_0_empty_n;
wire    F_acc_V_data_1_full_n;
wire   [31:0] F_acc_V_data_1_dout;
wire    F_acc_V_data_1_empty_n;
wire    F_acc_V_data_2_full_n;
wire   [31:0] F_acc_V_data_2_dout;
wire    F_acc_V_data_2_empty_n;
wire    F_acc_V_data_3_full_n;
wire   [31:0] F_acc_V_data_3_dout;
wire    F_acc_V_data_3_empty_n;
wire    V_acc_V_data_0_full_n;
wire   [31:0] V_acc_V_data_0_dout;
wire    V_acc_V_data_0_empty_n;
wire    V_acc_V_data_1_full_n;
wire   [31:0] V_acc_V_data_1_dout;
wire    V_acc_V_data_1_empty_n;
wire    V_acc_V_data_2_full_n;
wire   [31:0] V_acc_V_data_2_dout;
wire    V_acc_V_data_2_empty_n;
wire    V_acc_V_data_3_full_n;
wire   [31:0] V_acc_V_data_3_dout;
wire    V_acc_V_data_3_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_V_read_U0_din;
wire    start_for_V_read_U0_full_n;
wire   [0:0] start_for_V_read_U0_dout;
wire    start_for_V_read_U0_empty_n;
wire   [0:0] start_for_calc_U0_din;
wire    start_for_calc_U0_full_n;
wire   [0:0] start_for_calc_U0_dout;
wire    start_for_calc_U0_empty_n;
wire   [0:0] start_for_acc_U0_din;
wire    start_for_acc_U0_full_n;
wire   [0:0] start_for_acc_U0_dout;
wire    start_for_acc_U0_empty_n;
wire   [0:0] start_for_I_calc_U0_din;
wire    start_for_I_calc_U0_full_n;
wire   [0:0] start_for_I_calc_U0_dout;
wire    start_for_I_calc_U0_empty_n;
wire    I_calc_U0_start_full_n;
wire    I_calc_U0_start_write;

blockControl173 blockControl173_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(blockControl173_U0_ap_start),
    .start_full_n(start_for_V_read_U0_full_n),
    .ap_done(blockControl173_U0_ap_done),
    .ap_continue(blockControl173_U0_ap_continue),
    .ap_idle(blockControl173_U0_ap_idle),
    .ap_ready(blockControl173_U0_ap_ready),
    .start_out(blockControl173_U0_start_out),
    .start_write(blockControl173_U0_start_write),
    .input_V_data_TDATA(input_V_data_TDATA),
    .input_V_data_TVALID(input_V_data_TVALID),
    .input_V_data_TREADY(blockControl173_U0_input_V_data_TREADY),
    .V_SIZE(size),
    .p_read(simConfig_rowBegin_V_2),
    .p_read1(simConfig_rowEnd_V_r),
    .p_read2(simConfig_rowsToSimu),
    .p_read3(simConfig_BLOCK_NUMB),
    .simConfig_rowBegin_V_out_din(blockControl173_U0_simConfig_rowBegin_V_out_din),
    .simConfig_rowBegin_V_out_full_n(simConfig_rowBegin_V_full_n),
    .simConfig_rowBegin_V_out_write(blockControl173_U0_simConfig_rowBegin_V_out_write),
    .simConfig_rowEnd_V_out_din(blockControl173_U0_simConfig_rowEnd_V_out_din),
    .simConfig_rowEnd_V_out_full_n(simConfig_rowEnd_V_c_full_n),
    .simConfig_rowEnd_V_out_write(blockControl173_U0_simConfig_rowEnd_V_out_write),
    .simConfig_rowsToSimulate_V_out_din(blockControl173_U0_simConfig_rowsToSimulate_V_out_din),
    .simConfig_rowsToSimulate_V_out_full_n(simConfig_rowsToSimu_4_full_n),
    .simConfig_rowsToSimulate_V_out_write(blockControl173_U0_simConfig_rowsToSimulate_V_out_write),
    .simConfig_BLOCK_NUMBERS_V_out_din(blockControl173_U0_simConfig_BLOCK_NUMBERS_V_out_din),
    .simConfig_BLOCK_NUMBERS_V_out_full_n(simConfig_BLOCK_NUMB_4_full_n),
    .simConfig_BLOCK_NUMBERS_V_out_write(blockControl173_U0_simConfig_BLOCK_NUMBERS_V_out_write),
    .V_data_V_data_0_din(blockControl173_U0_V_data_V_data_0_din),
    .V_data_V_data_0_full_n(V_data_V_data_0_full_n),
    .V_data_V_data_0_write(blockControl173_U0_V_data_V_data_0_write),
    .V_data_V_data_1_din(blockControl173_U0_V_data_V_data_1_din),
    .V_data_V_data_1_full_n(V_data_V_data_1_full_n),
    .V_data_V_data_1_write(blockControl173_U0_V_data_V_data_1_write),
    .V_data_V_data_2_din(blockControl173_U0_V_data_V_data_2_din),
    .V_data_V_data_2_full_n(V_data_V_data_2_full_n),
    .V_data_V_data_2_write(blockControl173_U0_V_data_V_data_2_write),
    .V_data_V_data_3_din(blockControl173_U0_V_data_V_data_3_din),
    .V_data_V_data_3_full_n(V_data_V_data_3_full_n),
    .V_data_V_data_3_write(blockControl173_U0_V_data_V_data_3_write)
);

V_read V_read_U0(
    .ap_start(V_read_U0_ap_start),
    .start_full_n(start_for_calc_U0_full_n),
    .start_out(V_read_U0_start_out),
    .start_write(V_read_U0_start_write),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .simConfig_rowBegin_V_dout(simConfig_rowBegin_V_dout),
    .simConfig_rowBegin_V_empty_n(simConfig_rowBegin_V_empty_n),
    .simConfig_rowBegin_V_read(V_read_U0_simConfig_rowBegin_V_read),
    .simConfig_rowEnd_V_dout(simConfig_rowEnd_V_c_dout),
    .simConfig_rowEnd_V_empty_n(simConfig_rowEnd_V_c_empty_n),
    .simConfig_rowEnd_V_read(V_read_U0_simConfig_rowEnd_V_read),
    .simConfig_rowsToSimulate_V_dout(simConfig_rowsToSimu_4_dout),
    .simConfig_rowsToSimulate_V_empty_n(simConfig_rowsToSimu_4_empty_n),
    .simConfig_rowsToSimulate_V_read(V_read_U0_simConfig_rowsToSimulate_V_read),
    .simConfig_BLOCK_NUMBERS_V_dout(simConfig_BLOCK_NUMB_4_dout),
    .simConfig_BLOCK_NUMBERS_V_empty_n(simConfig_BLOCK_NUMB_4_empty_n),
    .simConfig_BLOCK_NUMBERS_V_read(V_read_U0_simConfig_BLOCK_NUMBERS_V_read),
    .V_SIZE(size),
    .simConfig_rowsToSimulate_V_out_din(V_read_U0_simConfig_rowsToSimulate_V_out_din),
    .simConfig_rowsToSimulate_V_out_full_n(simConfig_rowsToSimu_3_full_n),
    .simConfig_rowsToSimulate_V_out_write(V_read_U0_simConfig_rowsToSimulate_V_out_write),
    .simConfig_BLOCK_NUMBERS_V_out_din(V_read_U0_simConfig_BLOCK_NUMBERS_V_out_din),
    .simConfig_BLOCK_NUMBERS_V_out_full_n(simConfig_BLOCK_NUMB_3_full_n),
    .simConfig_BLOCK_NUMBERS_V_out_write(V_read_U0_simConfig_BLOCK_NUMBERS_V_out_write),
    .V_data_V_data_0_dout(V_data_V_data_0_dout),
    .V_data_V_data_0_empty_n(V_data_V_data_0_empty_n),
    .V_data_V_data_0_read(V_read_U0_V_data_V_data_0_read),
    .V_data_V_data_1_dout(V_data_V_data_1_dout),
    .V_data_V_data_1_empty_n(V_data_V_data_1_empty_n),
    .V_data_V_data_1_read(V_read_U0_V_data_V_data_1_read),
    .V_data_V_data_2_dout(V_data_V_data_2_dout),
    .V_data_V_data_2_empty_n(V_data_V_data_2_empty_n),
    .V_data_V_data_2_read(V_read_U0_V_data_V_data_2_read),
    .V_data_V_data_3_dout(V_data_V_data_3_dout),
    .V_data_V_data_3_empty_n(V_data_V_data_3_empty_n),
    .V_data_V_data_3_read(V_read_U0_V_data_V_data_3_read),
    .fixedData_V_data_din(V_read_U0_fixedData_V_data_din),
    .fixedData_V_data_full_n(fixedData_V_data_full_n),
    .fixedData_V_data_write(V_read_U0_fixedData_V_data_write),
    .fixedData_V_tlast_V_din(V_read_U0_fixedData_V_tlast_V_din),
    .fixedData_V_tlast_V_full_n(fixedData_V_tlast_V_full_n),
    .fixedData_V_tlast_V_write(V_read_U0_fixedData_V_tlast_V_write),
    .processedData_V_data_din(V_read_U0_processedData_V_data_din),
    .processedData_V_data_full_n(processedData_V_data_full_n),
    .processedData_V_data_write(V_read_U0_processedData_V_data_write),
    .processedData_V_data_1_din(V_read_U0_processedData_V_data_1_din),
    .processedData_V_data_1_full_n(processedData_V_data_1_full_n),
    .processedData_V_data_1_write(V_read_U0_processedData_V_data_1_write),
    .processedData_V_data_2_din(V_read_U0_processedData_V_data_2_din),
    .processedData_V_data_2_full_n(processedData_V_data_2_full_n),
    .processedData_V_data_2_write(V_read_U0_processedData_V_data_2_write),
    .processedData_V_data_3_din(V_read_U0_processedData_V_data_3_din),
    .processedData_V_data_3_full_n(processedData_V_data_3_full_n),
    .processedData_V_data_3_write(V_read_U0_processedData_V_data_3_write),
    .ap_done(V_read_U0_ap_done),
    .V_SIZE_ap_vld(size_ap_vld),
    .ap_ready(V_read_U0_ap_ready),
    .ap_idle(V_read_U0_ap_idle),
    .ap_continue(V_read_U0_ap_continue)
);

calc calc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(calc_U0_ap_start),
    .start_full_n(start_for_acc_U0_full_n),
    .ap_done(calc_U0_ap_done),
    .ap_continue(calc_U0_ap_continue),
    .ap_idle(calc_U0_ap_idle),
    .ap_ready(calc_U0_ap_ready),
    .start_out(calc_U0_start_out),
    .start_write(calc_U0_start_write),
    .simConfig_rowsToSimulate_V_dout(simConfig_rowsToSimu_3_dout),
    .simConfig_rowsToSimulate_V_empty_n(simConfig_rowsToSimu_3_empty_n),
    .simConfig_rowsToSimulate_V_read(calc_U0_simConfig_rowsToSimulate_V_read),
    .simConfig_BLOCK_NUMBERS_V_dout(simConfig_BLOCK_NUMB_3_dout),
    .simConfig_BLOCK_NUMBERS_V_empty_n(simConfig_BLOCK_NUMB_3_empty_n),
    .simConfig_BLOCK_NUMBERS_V_read(calc_U0_simConfig_BLOCK_NUMBERS_V_read),
    .simConfig_rowsToSimulate_V_out_din(calc_U0_simConfig_rowsToSimulate_V_out_din),
    .simConfig_rowsToSimulate_V_out_full_n(simConfig_rowsToSimu_2_full_n),
    .simConfig_rowsToSimulate_V_out_write(calc_U0_simConfig_rowsToSimulate_V_out_write),
    .simConfig_BLOCK_NUMBERS_V_out_din(calc_U0_simConfig_BLOCK_NUMBERS_V_out_din),
    .simConfig_BLOCK_NUMBERS_V_out_full_n(simConfig_BLOCK_NUMB_2_full_n),
    .simConfig_BLOCK_NUMBERS_V_out_write(calc_U0_simConfig_BLOCK_NUMBERS_V_out_write),
    .processedData_V_data_dout(processedData_V_data_dout),
    .processedData_V_data_empty_n(processedData_V_data_empty_n),
    .processedData_V_data_read(calc_U0_processedData_V_data_read),
    .processedData_V_data_1_dout(processedData_V_data_1_dout),
    .processedData_V_data_1_empty_n(processedData_V_data_1_empty_n),
    .processedData_V_data_1_read(calc_U0_processedData_V_data_1_read),
    .processedData_V_data_2_dout(processedData_V_data_2_dout),
    .processedData_V_data_2_empty_n(processedData_V_data_2_empty_n),
    .processedData_V_data_2_read(calc_U0_processedData_V_data_2_read),
    .processedData_V_data_3_dout(processedData_V_data_3_dout),
    .processedData_V_data_3_empty_n(processedData_V_data_3_empty_n),
    .processedData_V_data_3_read(calc_U0_processedData_V_data_3_read),
    .fixedData_V_data_dout(fixedData_V_data_dout),
    .fixedData_V_data_empty_n(fixedData_V_data_empty_n),
    .fixedData_V_data_read(calc_U0_fixedData_V_data_read),
    .fixedData_V_tlast_V_dout(fixedData_V_tlast_V_dout),
    .fixedData_V_tlast_V_empty_n(fixedData_V_tlast_V_empty_n),
    .fixedData_V_tlast_V_read(calc_U0_fixedData_V_tlast_V_read),
    .V_V_data_0_din(calc_U0_V_V_data_0_din),
    .V_V_data_0_full_n(V_V_data_0_full_n),
    .V_V_data_0_write(calc_U0_V_V_data_0_write),
    .V_V_data_1_din(calc_U0_V_V_data_1_din),
    .V_V_data_1_full_n(V_V_data_1_full_n),
    .V_V_data_1_write(calc_U0_V_V_data_1_write),
    .V_V_data_2_din(calc_U0_V_V_data_2_din),
    .V_V_data_2_full_n(V_V_data_2_full_n),
    .V_V_data_2_write(calc_U0_V_V_data_2_write),
    .V_V_data_3_din(calc_U0_V_V_data_3_din),
    .V_V_data_3_full_n(V_V_data_3_full_n),
    .V_V_data_3_write(calc_U0_V_V_data_3_write),
    .F_V_data_0_din(calc_U0_F_V_data_0_din),
    .F_V_data_0_full_n(F_V_data_0_full_n),
    .F_V_data_0_write(calc_U0_F_V_data_0_write),
    .F_V_data_1_din(calc_U0_F_V_data_1_din),
    .F_V_data_1_full_n(F_V_data_1_full_n),
    .F_V_data_1_write(calc_U0_F_V_data_1_write),
    .F_V_data_2_din(calc_U0_F_V_data_2_din),
    .F_V_data_2_full_n(F_V_data_2_full_n),
    .F_V_data_2_write(calc_U0_F_V_data_2_write),
    .F_V_data_3_din(calc_U0_F_V_data_3_din),
    .F_V_data_3_full_n(F_V_data_3_full_n),
    .F_V_data_3_write(calc_U0_F_V_data_3_write)
);

acc acc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(acc_U0_ap_start),
    .start_full_n(start_for_I_calc_U0_full_n),
    .ap_done(acc_U0_ap_done),
    .ap_continue(acc_U0_ap_continue),
    .ap_idle(acc_U0_ap_idle),
    .ap_ready(acc_U0_ap_ready),
    .start_out(acc_U0_start_out),
    .start_write(acc_U0_start_write),
    .simConfig_rowsToSimulate_V_dout(simConfig_rowsToSimu_2_dout),
    .simConfig_rowsToSimulate_V_empty_n(simConfig_rowsToSimu_2_empty_n),
    .simConfig_rowsToSimulate_V_read(acc_U0_simConfig_rowsToSimulate_V_read),
    .simConfig_BLOCK_NUMBERS_V_dout(simConfig_BLOCK_NUMB_2_dout),
    .simConfig_BLOCK_NUMBERS_V_empty_n(simConfig_BLOCK_NUMB_2_empty_n),
    .simConfig_BLOCK_NUMBERS_V_read(acc_U0_simConfig_BLOCK_NUMBERS_V_read),
    .simConfig_rowsToSimulate_V_out_din(acc_U0_simConfig_rowsToSimulate_V_out_din),
    .simConfig_rowsToSimulate_V_out_full_n(simConfig_rowsToSimu_1_full_n),
    .simConfig_rowsToSimulate_V_out_write(acc_U0_simConfig_rowsToSimulate_V_out_write),
    .simConfig_BLOCK_NUMBERS_V_out_din(acc_U0_simConfig_BLOCK_NUMBERS_V_out_din),
    .simConfig_BLOCK_NUMBERS_V_out_full_n(simConfig_BLOCK_NUMB_1_full_n),
    .simConfig_BLOCK_NUMBERS_V_out_write(acc_U0_simConfig_BLOCK_NUMBERS_V_out_write),
    .F_V_data_0_dout(F_V_data_0_dout),
    .F_V_data_0_empty_n(F_V_data_0_empty_n),
    .F_V_data_0_read(acc_U0_F_V_data_0_read),
    .F_V_data_1_dout(F_V_data_1_dout),
    .F_V_data_1_empty_n(F_V_data_1_empty_n),
    .F_V_data_1_read(acc_U0_F_V_data_1_read),
    .F_V_data_2_dout(F_V_data_2_dout),
    .F_V_data_2_empty_n(F_V_data_2_empty_n),
    .F_V_data_2_read(acc_U0_F_V_data_2_read),
    .F_V_data_3_dout(F_V_data_3_dout),
    .F_V_data_3_empty_n(F_V_data_3_empty_n),
    .F_V_data_3_read(acc_U0_F_V_data_3_read),
    .V_V_data_0_dout(V_V_data_0_dout),
    .V_V_data_0_empty_n(V_V_data_0_empty_n),
    .V_V_data_0_read(acc_U0_V_V_data_0_read),
    .V_V_data_1_dout(V_V_data_1_dout),
    .V_V_data_1_empty_n(V_V_data_1_empty_n),
    .V_V_data_1_read(acc_U0_V_V_data_1_read),
    .V_V_data_2_dout(V_V_data_2_dout),
    .V_V_data_2_empty_n(V_V_data_2_empty_n),
    .V_V_data_2_read(acc_U0_V_V_data_2_read),
    .V_V_data_3_dout(V_V_data_3_dout),
    .V_V_data_3_empty_n(V_V_data_3_empty_n),
    .V_V_data_3_read(acc_U0_V_V_data_3_read),
    .F_acc_V_data_0_din(acc_U0_F_acc_V_data_0_din),
    .F_acc_V_data_0_full_n(F_acc_V_data_0_full_n),
    .F_acc_V_data_0_write(acc_U0_F_acc_V_data_0_write),
    .F_acc_V_data_1_din(acc_U0_F_acc_V_data_1_din),
    .F_acc_V_data_1_full_n(F_acc_V_data_1_full_n),
    .F_acc_V_data_1_write(acc_U0_F_acc_V_data_1_write),
    .F_acc_V_data_2_din(acc_U0_F_acc_V_data_2_din),
    .F_acc_V_data_2_full_n(F_acc_V_data_2_full_n),
    .F_acc_V_data_2_write(acc_U0_F_acc_V_data_2_write),
    .F_acc_V_data_3_din(acc_U0_F_acc_V_data_3_din),
    .F_acc_V_data_3_full_n(F_acc_V_data_3_full_n),
    .F_acc_V_data_3_write(acc_U0_F_acc_V_data_3_write),
    .V_acc_V_data_0_din(acc_U0_V_acc_V_data_0_din),
    .V_acc_V_data_0_full_n(V_acc_V_data_0_full_n),
    .V_acc_V_data_0_write(acc_U0_V_acc_V_data_0_write),
    .V_acc_V_data_1_din(acc_U0_V_acc_V_data_1_din),
    .V_acc_V_data_1_full_n(V_acc_V_data_1_full_n),
    .V_acc_V_data_1_write(acc_U0_V_acc_V_data_1_write),
    .V_acc_V_data_2_din(acc_U0_V_acc_V_data_2_din),
    .V_acc_V_data_2_full_n(V_acc_V_data_2_full_n),
    .V_acc_V_data_2_write(acc_U0_V_acc_V_data_2_write),
    .V_acc_V_data_3_din(acc_U0_V_acc_V_data_3_din),
    .V_acc_V_data_3_full_n(V_acc_V_data_3_full_n),
    .V_acc_V_data_3_write(acc_U0_V_acc_V_data_3_write)
);

I_calc I_calc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(I_calc_U0_ap_start),
    .ap_done(I_calc_U0_ap_done),
    .ap_continue(I_calc_U0_ap_continue),
    .ap_idle(I_calc_U0_ap_idle),
    .ap_ready(I_calc_U0_ap_ready),
    .output_r_TDATA(I_calc_U0_output_r_TDATA),
    .output_r_TVALID(I_calc_U0_output_r_TVALID),
    .output_r_TREADY(output_r_TREADY),
    .output_r_TLAST(I_calc_U0_output_r_TLAST),
    .simConfig_rowsToSimulate_V_dout(simConfig_rowsToSimu_1_dout),
    .simConfig_rowsToSimulate_V_empty_n(simConfig_rowsToSimu_1_empty_n),
    .simConfig_rowsToSimulate_V_read(I_calc_U0_simConfig_rowsToSimulate_V_read),
    .simConfig_BLOCK_NUMBERS_V_dout(simConfig_BLOCK_NUMB_1_dout),
    .simConfig_BLOCK_NUMBERS_V_empty_n(simConfig_BLOCK_NUMB_1_empty_n),
    .simConfig_BLOCK_NUMBERS_V_read(I_calc_U0_simConfig_BLOCK_NUMBERS_V_read),
    .F_acc_V_data_0_dout(F_acc_V_data_0_dout),
    .F_acc_V_data_0_empty_n(F_acc_V_data_0_empty_n),
    .F_acc_V_data_0_read(I_calc_U0_F_acc_V_data_0_read),
    .F_acc_V_data_1_dout(F_acc_V_data_1_dout),
    .F_acc_V_data_1_empty_n(F_acc_V_data_1_empty_n),
    .F_acc_V_data_1_read(I_calc_U0_F_acc_V_data_1_read),
    .F_acc_V_data_2_dout(F_acc_V_data_2_dout),
    .F_acc_V_data_2_empty_n(F_acc_V_data_2_empty_n),
    .F_acc_V_data_2_read(I_calc_U0_F_acc_V_data_2_read),
    .F_acc_V_data_3_dout(F_acc_V_data_3_dout),
    .F_acc_V_data_3_empty_n(F_acc_V_data_3_empty_n),
    .F_acc_V_data_3_read(I_calc_U0_F_acc_V_data_3_read),
    .V_acc_V_data_0_dout(V_acc_V_data_0_dout),
    .V_acc_V_data_0_empty_n(V_acc_V_data_0_empty_n),
    .V_acc_V_data_0_read(I_calc_U0_V_acc_V_data_0_read),
    .V_acc_V_data_1_dout(V_acc_V_data_1_dout),
    .V_acc_V_data_1_empty_n(V_acc_V_data_1_empty_n),
    .V_acc_V_data_1_read(I_calc_U0_V_acc_V_data_1_read),
    .V_acc_V_data_2_dout(V_acc_V_data_2_dout),
    .V_acc_V_data_2_empty_n(V_acc_V_data_2_empty_n),
    .V_acc_V_data_2_read(I_calc_U0_V_acc_V_data_2_read),
    .V_acc_V_data_3_dout(V_acc_V_data_3_dout),
    .V_acc_V_data_3_empty_n(V_acc_V_data_3_empty_n),
    .V_acc_V_data_3_read(I_calc_U0_V_acc_V_data_3_read)
);

fifo_w27_d2_A_x simConfig_rowBegin_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blockControl173_U0_simConfig_rowBegin_V_out_din),
    .if_full_n(simConfig_rowBegin_V_full_n),
    .if_write(blockControl173_U0_simConfig_rowBegin_V_out_write),
    .if_dout(simConfig_rowBegin_V_dout),
    .if_empty_n(simConfig_rowBegin_V_empty_n),
    .if_read(V_read_U0_simConfig_rowBegin_V_read)
);

fifo_w27_d2_A_x simConfig_rowEnd_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blockControl173_U0_simConfig_rowEnd_V_out_din),
    .if_full_n(simConfig_rowEnd_V_c_full_n),
    .if_write(blockControl173_U0_simConfig_rowEnd_V_out_write),
    .if_dout(simConfig_rowEnd_V_c_dout),
    .if_empty_n(simConfig_rowEnd_V_c_empty_n),
    .if_read(V_read_U0_simConfig_rowEnd_V_read)
);

fifo_w27_d2_A_x simConfig_rowsToSimu_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blockControl173_U0_simConfig_rowsToSimulate_V_out_din),
    .if_full_n(simConfig_rowsToSimu_4_full_n),
    .if_write(blockControl173_U0_simConfig_rowsToSimulate_V_out_write),
    .if_dout(simConfig_rowsToSimu_4_dout),
    .if_empty_n(simConfig_rowsToSimu_4_empty_n),
    .if_read(V_read_U0_simConfig_rowsToSimulate_V_read)
);

fifo_w27_d2_A_x simConfig_BLOCK_NUMB_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blockControl173_U0_simConfig_BLOCK_NUMBERS_V_out_din),
    .if_full_n(simConfig_BLOCK_NUMB_4_full_n),
    .if_write(blockControl173_U0_simConfig_BLOCK_NUMBERS_V_out_write),
    .if_dout(simConfig_BLOCK_NUMB_4_dout),
    .if_empty_n(simConfig_BLOCK_NUMB_4_empty_n),
    .if_read(V_read_U0_simConfig_BLOCK_NUMBERS_V_read)
);

fifo_w32_d128_A V_data_V_data_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blockControl173_U0_V_data_V_data_0_din),
    .if_full_n(V_data_V_data_0_full_n),
    .if_write(blockControl173_U0_V_data_V_data_0_write),
    .if_dout(V_data_V_data_0_dout),
    .if_empty_n(V_data_V_data_0_empty_n),
    .if_read(V_read_U0_V_data_V_data_0_read)
);

fifo_w32_d128_A V_data_V_data_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blockControl173_U0_V_data_V_data_1_din),
    .if_full_n(V_data_V_data_1_full_n),
    .if_write(blockControl173_U0_V_data_V_data_1_write),
    .if_dout(V_data_V_data_1_dout),
    .if_empty_n(V_data_V_data_1_empty_n),
    .if_read(V_read_U0_V_data_V_data_1_read)
);

fifo_w32_d128_A V_data_V_data_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blockControl173_U0_V_data_V_data_2_din),
    .if_full_n(V_data_V_data_2_full_n),
    .if_write(blockControl173_U0_V_data_V_data_2_write),
    .if_dout(V_data_V_data_2_dout),
    .if_empty_n(V_data_V_data_2_empty_n),
    .if_read(V_read_U0_V_data_V_data_2_read)
);

fifo_w32_d128_A V_data_V_data_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(blockControl173_U0_V_data_V_data_3_din),
    .if_full_n(V_data_V_data_3_full_n),
    .if_write(blockControl173_U0_V_data_V_data_3_write),
    .if_dout(V_data_V_data_3_dout),
    .if_empty_n(V_data_V_data_3_empty_n),
    .if_read(V_read_U0_V_data_V_data_3_read)
);

fifo_w27_d2_A_x simConfig_rowsToSimu_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(V_read_U0_simConfig_rowsToSimulate_V_out_din),
    .if_full_n(simConfig_rowsToSimu_3_full_n),
    .if_write(V_read_U0_simConfig_rowsToSimulate_V_out_write),
    .if_dout(simConfig_rowsToSimu_3_dout),
    .if_empty_n(simConfig_rowsToSimu_3_empty_n),
    .if_read(calc_U0_simConfig_rowsToSimulate_V_read)
);

fifo_w27_d2_A_x simConfig_BLOCK_NUMB_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(V_read_U0_simConfig_BLOCK_NUMBERS_V_out_din),
    .if_full_n(simConfig_BLOCK_NUMB_3_full_n),
    .if_write(V_read_U0_simConfig_BLOCK_NUMBERS_V_out_write),
    .if_dout(simConfig_BLOCK_NUMB_3_dout),
    .if_empty_n(simConfig_BLOCK_NUMB_3_empty_n),
    .if_read(calc_U0_simConfig_BLOCK_NUMBERS_V_read)
);

fifo_w32_d128_A fixedData_V_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(V_read_U0_fixedData_V_data_din),
    .if_full_n(fixedData_V_data_full_n),
    .if_write(V_read_U0_fixedData_V_data_write),
    .if_dout(fixedData_V_data_dout),
    .if_empty_n(fixedData_V_data_empty_n),
    .if_read(calc_U0_fixedData_V_data_read)
);

fifo_w1_d128_A fixedData_V_tlast_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(V_read_U0_fixedData_V_tlast_V_din),
    .if_full_n(fixedData_V_tlast_V_full_n),
    .if_write(V_read_U0_fixedData_V_tlast_V_write),
    .if_dout(fixedData_V_tlast_V_dout),
    .if_empty_n(fixedData_V_tlast_V_empty_n),
    .if_read(calc_U0_fixedData_V_tlast_V_read)
);

fifo_w32_d128_A processedData_V_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(V_read_U0_processedData_V_data_din),
    .if_full_n(processedData_V_data_full_n),
    .if_write(V_read_U0_processedData_V_data_write),
    .if_dout(processedData_V_data_dout),
    .if_empty_n(processedData_V_data_empty_n),
    .if_read(calc_U0_processedData_V_data_read)
);

fifo_w32_d128_A processedData_V_data_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(V_read_U0_processedData_V_data_1_din),
    .if_full_n(processedData_V_data_1_full_n),
    .if_write(V_read_U0_processedData_V_data_1_write),
    .if_dout(processedData_V_data_1_dout),
    .if_empty_n(processedData_V_data_1_empty_n),
    .if_read(calc_U0_processedData_V_data_1_read)
);

fifo_w32_d128_A processedData_V_data_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(V_read_U0_processedData_V_data_2_din),
    .if_full_n(processedData_V_data_2_full_n),
    .if_write(V_read_U0_processedData_V_data_2_write),
    .if_dout(processedData_V_data_2_dout),
    .if_empty_n(processedData_V_data_2_empty_n),
    .if_read(calc_U0_processedData_V_data_2_read)
);

fifo_w32_d128_A processedData_V_data_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(V_read_U0_processedData_V_data_3_din),
    .if_full_n(processedData_V_data_3_full_n),
    .if_write(V_read_U0_processedData_V_data_3_write),
    .if_dout(processedData_V_data_3_dout),
    .if_empty_n(processedData_V_data_3_empty_n),
    .if_read(calc_U0_processedData_V_data_3_read)
);

fifo_w27_d2_A_x simConfig_rowsToSimu_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(calc_U0_simConfig_rowsToSimulate_V_out_din),
    .if_full_n(simConfig_rowsToSimu_2_full_n),
    .if_write(calc_U0_simConfig_rowsToSimulate_V_out_write),
    .if_dout(simConfig_rowsToSimu_2_dout),
    .if_empty_n(simConfig_rowsToSimu_2_empty_n),
    .if_read(acc_U0_simConfig_rowsToSimulate_V_read)
);

fifo_w27_d2_A_x simConfig_BLOCK_NUMB_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(calc_U0_simConfig_BLOCK_NUMBERS_V_out_din),
    .if_full_n(simConfig_BLOCK_NUMB_2_full_n),
    .if_write(calc_U0_simConfig_BLOCK_NUMBERS_V_out_write),
    .if_dout(simConfig_BLOCK_NUMB_2_dout),
    .if_empty_n(simConfig_BLOCK_NUMB_2_empty_n),
    .if_read(acc_U0_simConfig_BLOCK_NUMBERS_V_read)
);

fifo_w32_d128_A V_V_data_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(calc_U0_V_V_data_0_din),
    .if_full_n(V_V_data_0_full_n),
    .if_write(calc_U0_V_V_data_0_write),
    .if_dout(V_V_data_0_dout),
    .if_empty_n(V_V_data_0_empty_n),
    .if_read(acc_U0_V_V_data_0_read)
);

fifo_w32_d128_A V_V_data_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(calc_U0_V_V_data_1_din),
    .if_full_n(V_V_data_1_full_n),
    .if_write(calc_U0_V_V_data_1_write),
    .if_dout(V_V_data_1_dout),
    .if_empty_n(V_V_data_1_empty_n),
    .if_read(acc_U0_V_V_data_1_read)
);

fifo_w32_d128_A V_V_data_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(calc_U0_V_V_data_2_din),
    .if_full_n(V_V_data_2_full_n),
    .if_write(calc_U0_V_V_data_2_write),
    .if_dout(V_V_data_2_dout),
    .if_empty_n(V_V_data_2_empty_n),
    .if_read(acc_U0_V_V_data_2_read)
);

fifo_w32_d128_A V_V_data_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(calc_U0_V_V_data_3_din),
    .if_full_n(V_V_data_3_full_n),
    .if_write(calc_U0_V_V_data_3_write),
    .if_dout(V_V_data_3_dout),
    .if_empty_n(V_V_data_3_empty_n),
    .if_read(acc_U0_V_V_data_3_read)
);

fifo_w32_d128_A F_V_data_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(calc_U0_F_V_data_0_din),
    .if_full_n(F_V_data_0_full_n),
    .if_write(calc_U0_F_V_data_0_write),
    .if_dout(F_V_data_0_dout),
    .if_empty_n(F_V_data_0_empty_n),
    .if_read(acc_U0_F_V_data_0_read)
);

fifo_w32_d128_A F_V_data_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(calc_U0_F_V_data_1_din),
    .if_full_n(F_V_data_1_full_n),
    .if_write(calc_U0_F_V_data_1_write),
    .if_dout(F_V_data_1_dout),
    .if_empty_n(F_V_data_1_empty_n),
    .if_read(acc_U0_F_V_data_1_read)
);

fifo_w32_d128_A F_V_data_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(calc_U0_F_V_data_2_din),
    .if_full_n(F_V_data_2_full_n),
    .if_write(calc_U0_F_V_data_2_write),
    .if_dout(F_V_data_2_dout),
    .if_empty_n(F_V_data_2_empty_n),
    .if_read(acc_U0_F_V_data_2_read)
);

fifo_w32_d128_A F_V_data_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(calc_U0_F_V_data_3_din),
    .if_full_n(F_V_data_3_full_n),
    .if_write(calc_U0_F_V_data_3_write),
    .if_dout(F_V_data_3_dout),
    .if_empty_n(F_V_data_3_empty_n),
    .if_read(acc_U0_F_V_data_3_read)
);

fifo_w27_d2_A_x simConfig_rowsToSimu_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(acc_U0_simConfig_rowsToSimulate_V_out_din),
    .if_full_n(simConfig_rowsToSimu_1_full_n),
    .if_write(acc_U0_simConfig_rowsToSimulate_V_out_write),
    .if_dout(simConfig_rowsToSimu_1_dout),
    .if_empty_n(simConfig_rowsToSimu_1_empty_n),
    .if_read(I_calc_U0_simConfig_rowsToSimulate_V_read)
);

fifo_w27_d2_A_x simConfig_BLOCK_NUMB_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(acc_U0_simConfig_BLOCK_NUMBERS_V_out_din),
    .if_full_n(simConfig_BLOCK_NUMB_1_full_n),
    .if_write(acc_U0_simConfig_BLOCK_NUMBERS_V_out_write),
    .if_dout(simConfig_BLOCK_NUMB_1_dout),
    .if_empty_n(simConfig_BLOCK_NUMB_1_empty_n),
    .if_read(I_calc_U0_simConfig_BLOCK_NUMBERS_V_read)
);

fifo_w32_d128_A F_acc_V_data_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(acc_U0_F_acc_V_data_0_din),
    .if_full_n(F_acc_V_data_0_full_n),
    .if_write(acc_U0_F_acc_V_data_0_write),
    .if_dout(F_acc_V_data_0_dout),
    .if_empty_n(F_acc_V_data_0_empty_n),
    .if_read(I_calc_U0_F_acc_V_data_0_read)
);

fifo_w32_d128_A F_acc_V_data_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(acc_U0_F_acc_V_data_1_din),
    .if_full_n(F_acc_V_data_1_full_n),
    .if_write(acc_U0_F_acc_V_data_1_write),
    .if_dout(F_acc_V_data_1_dout),
    .if_empty_n(F_acc_V_data_1_empty_n),
    .if_read(I_calc_U0_F_acc_V_data_1_read)
);

fifo_w32_d128_A F_acc_V_data_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(acc_U0_F_acc_V_data_2_din),
    .if_full_n(F_acc_V_data_2_full_n),
    .if_write(acc_U0_F_acc_V_data_2_write),
    .if_dout(F_acc_V_data_2_dout),
    .if_empty_n(F_acc_V_data_2_empty_n),
    .if_read(I_calc_U0_F_acc_V_data_2_read)
);

fifo_w32_d128_A F_acc_V_data_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(acc_U0_F_acc_V_data_3_din),
    .if_full_n(F_acc_V_data_3_full_n),
    .if_write(acc_U0_F_acc_V_data_3_write),
    .if_dout(F_acc_V_data_3_dout),
    .if_empty_n(F_acc_V_data_3_empty_n),
    .if_read(I_calc_U0_F_acc_V_data_3_read)
);

fifo_w32_d128_A V_acc_V_data_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(acc_U0_V_acc_V_data_0_din),
    .if_full_n(V_acc_V_data_0_full_n),
    .if_write(acc_U0_V_acc_V_data_0_write),
    .if_dout(V_acc_V_data_0_dout),
    .if_empty_n(V_acc_V_data_0_empty_n),
    .if_read(I_calc_U0_V_acc_V_data_0_read)
);

fifo_w32_d128_A V_acc_V_data_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(acc_U0_V_acc_V_data_1_din),
    .if_full_n(V_acc_V_data_1_full_n),
    .if_write(acc_U0_V_acc_V_data_1_write),
    .if_dout(V_acc_V_data_1_dout),
    .if_empty_n(V_acc_V_data_1_empty_n),
    .if_read(I_calc_U0_V_acc_V_data_1_read)
);

fifo_w32_d128_A V_acc_V_data_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(acc_U0_V_acc_V_data_2_din),
    .if_full_n(V_acc_V_data_2_full_n),
    .if_write(acc_U0_V_acc_V_data_2_write),
    .if_dout(V_acc_V_data_2_dout),
    .if_empty_n(V_acc_V_data_2_empty_n),
    .if_read(I_calc_U0_V_acc_V_data_2_read)
);

fifo_w32_d128_A V_acc_V_data_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(acc_U0_V_acc_V_data_3_din),
    .if_full_n(V_acc_V_data_3_full_n),
    .if_write(acc_U0_V_acc_V_data_3_write),
    .if_dout(V_acc_V_data_3_dout),
    .if_empty_n(V_acc_V_data_3_empty_n),
    .if_read(I_calc_U0_V_acc_V_data_3_read)
);

start_for_V_read_U0 start_for_V_read_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_V_read_U0_din),
    .if_full_n(start_for_V_read_U0_full_n),
    .if_write(blockControl173_U0_start_write),
    .if_dout(start_for_V_read_U0_dout),
    .if_empty_n(start_for_V_read_U0_empty_n),
    .if_read(V_read_U0_ap_ready)
);

start_for_calc_U0 start_for_calc_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_calc_U0_din),
    .if_full_n(start_for_calc_U0_full_n),
    .if_write(V_read_U0_start_write),
    .if_dout(start_for_calc_U0_dout),
    .if_empty_n(start_for_calc_U0_empty_n),
    .if_read(calc_U0_ap_ready)
);

start_for_acc_U0 start_for_acc_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_acc_U0_din),
    .if_full_n(start_for_acc_U0_full_n),
    .if_write(calc_U0_start_write),
    .if_dout(start_for_acc_U0_dout),
    .if_empty_n(start_for_acc_U0_empty_n),
    .if_read(acc_U0_ap_ready)
);

start_for_I_calc_U0 start_for_I_calc_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_I_calc_U0_din),
    .if_full_n(start_for_I_calc_U0_full_n),
    .if_write(acc_U0_start_write),
    .if_dout(start_for_I_calc_U0_dout),
    .if_empty_n(start_for_I_calc_U0_empty_n),
    .if_read(I_calc_U0_ap_ready)
);

assign I_calc_U0_ap_continue = ap_continue;

assign I_calc_U0_ap_start = start_for_I_calc_U0_empty_n;

assign I_calc_U0_start_full_n = 1'b1;

assign I_calc_U0_start_write = 1'b0;

assign V_read_U0_ap_continue = 1'b1;

assign V_read_U0_ap_start = start_for_V_read_U0_empty_n;

assign acc_U0_ap_continue = 1'b1;

assign acc_U0_ap_start = start_for_acc_U0_empty_n;

assign ap_done = I_calc_U0_ap_done;

assign ap_idle = (calc_U0_ap_idle & blockControl173_U0_ap_idle & acc_U0_ap_idle & V_read_U0_ap_idle & I_calc_U0_ap_idle);

assign ap_ready = blockControl173_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = I_calc_U0_ap_done;

assign ap_sync_ready = blockControl173_U0_ap_ready;

assign blockControl173_U0_ap_continue = 1'b1;

assign blockControl173_U0_ap_start = ap_start;

assign calc_U0_ap_continue = 1'b1;

assign calc_U0_ap_start = start_for_calc_U0_empty_n;

assign input_V_data_TREADY = blockControl173_U0_input_V_data_TREADY;

assign output_r_TDATA = I_calc_U0_output_r_TDATA;

assign output_r_TLAST = I_calc_U0_output_r_TLAST;

assign output_r_TVALID = I_calc_U0_output_r_TVALID;

assign start_for_I_calc_U0_din = 1'b1;

assign start_for_V_read_U0_din = 1'b1;

assign start_for_acc_U0_din = 1'b1;

assign start_for_calc_U0_din = 1'b1;

endmodule //execute
