-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GapJunctionIP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_V_data_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    input_V_data_TVALID : IN STD_LOGIC;
    input_V_data_TREADY : OUT STD_LOGIC;
    output_r_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_r_TVALID : OUT STD_LOGIC;
    output_r_TREADY : IN STD_LOGIC;
    output_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    size : IN STD_LOGIC_VECTOR (31 downto 0);
    FirstRow : IN STD_LOGIC_VECTOR (31 downto 0);
    LastRow : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of GapJunctionIP is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "GapJunctionIP,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z045ffg900-2,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.375000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=102,HLS_SYN_DSP=76,HLS_SYN_FF=14002,HLS_SYN_LUT=14397,HLS_VERSION=2018_3}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv27_0 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal input_V_data_0_data_out : STD_LOGIC_VECTOR (63 downto 0);
    signal input_V_data_0_vld_in : STD_LOGIC;
    signal input_V_data_0_vld_out : STD_LOGIC;
    signal input_V_data_0_ack_in : STD_LOGIC;
    signal input_V_data_0_ack_out : STD_LOGIC;
    signal input_V_data_0_payload_A : STD_LOGIC_VECTOR (63 downto 0);
    signal input_V_data_0_payload_B : STD_LOGIC_VECTOR (63 downto 0);
    signal input_V_data_0_sel_rd : STD_LOGIC := '0';
    signal input_V_data_0_sel_wr : STD_LOGIC := '0';
    signal input_V_data_0_sel : STD_LOGIC;
    signal input_V_data_0_load_A : STD_LOGIC;
    signal input_V_data_0_load_B : STD_LOGIC;
    signal input_V_data_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal input_V_data_0_state_cmp_full : STD_LOGIC;
    signal output_V_data_1_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal output_V_data_1_vld_in : STD_LOGIC;
    signal output_V_data_1_vld_out : STD_LOGIC;
    signal output_V_data_1_ack_in : STD_LOGIC;
    signal output_V_data_1_ack_out : STD_LOGIC;
    signal output_V_data_1_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal output_V_data_1_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal output_V_data_1_sel_rd : STD_LOGIC := '0';
    signal output_V_data_1_sel_wr : STD_LOGIC := '0';
    signal output_V_data_1_sel : STD_LOGIC;
    signal output_V_data_1_load_A : STD_LOGIC;
    signal output_V_data_1_load_B : STD_LOGIC;
    signal output_V_data_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal output_V_data_1_state_cmp_full : STD_LOGIC;
    signal output_V_tlast_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal output_V_tlast_V_1_vld_in : STD_LOGIC;
    signal output_V_tlast_V_1_vld_out : STD_LOGIC;
    signal output_V_tlast_V_1_ack_in : STD_LOGIC;
    signal output_V_tlast_V_1_ack_out : STD_LOGIC;
    signal output_V_tlast_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal output_V_tlast_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal output_V_tlast_V_1_sel_rd : STD_LOGIC := '0';
    signal output_V_tlast_V_1_sel_wr : STD_LOGIC := '0';
    signal output_V_tlast_V_1_sel : STD_LOGIC;
    signal output_V_tlast_V_1_load_A : STD_LOGIC;
    signal output_V_tlast_V_1_load_B : STD_LOGIC;
    signal output_V_tlast_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal output_V_tlast_V_1_state_cmp_full : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal tmp_4_fu_239_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_253_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_6_fu_263_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_10_fu_284_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_308_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_9_fu_314_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_execute_fu_142_output_r_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_execute_fu_142_output_r_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_execute_fu_142_simConfig_rowBegin_V_2 : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_execute_fu_142_simConfig_rowEnd_V_r : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_execute_fu_142_simConfig_rowsToSimu : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_execute_fu_142_simConfig_BLOCK_NUMB : STD_LOGIC_VECTOR (26 downto 0);
    signal grp_execute_fu_142_input_V_data_TVALID : STD_LOGIC;
    signal grp_execute_fu_142_input_V_data_TREADY : STD_LOGIC;
    signal grp_execute_fu_142_ap_start : STD_LOGIC;
    signal grp_execute_fu_142_output_r_TVALID : STD_LOGIC;
    signal grp_execute_fu_142_output_r_TREADY : STD_LOGIC;
    signal grp_execute_fu_142_ap_done : STD_LOGIC;
    signal grp_execute_fu_142_ap_ready : STD_LOGIC;
    signal grp_execute_fu_142_ap_idle : STD_LOGIC;
    signal grp_execute_fu_142_ap_continue : STD_LOGIC;
    signal grp_execute_fu_142_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_sync_grp_execute_fu_142_ap_ready : STD_LOGIC;
    signal ap_sync_grp_execute_fu_142_ap_done : STD_LOGIC;
    signal ap_block_state4_on_subcall_done : BOOLEAN;
    signal ap_sync_reg_grp_execute_fu_142_ap_ready : STD_LOGIC := '0';
    signal ap_sync_reg_grp_execute_fu_142_ap_done : STD_LOGIC := '0';
    signal tmp_s_fu_233_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_neg6_fu_247_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_273_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_neg_fu_292_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_298_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_block_state5 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);

    component execute IS
    port (
        input_V_data_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        output_r_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        output_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        simConfig_rowBegin_V_2 : IN STD_LOGIC_VECTOR (26 downto 0);
        simConfig_rowEnd_V_r : IN STD_LOGIC_VECTOR (26 downto 0);
        simConfig_rowsToSimu : IN STD_LOGIC_VECTOR (26 downto 0);
        simConfig_BLOCK_NUMB : IN STD_LOGIC_VECTOR (26 downto 0);
        size : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        input_V_data_TVALID : IN STD_LOGIC;
        input_V_data_TREADY : OUT STD_LOGIC;
        size_ap_vld : IN STD_LOGIC;
        simConfig_rowBegin_V_2_ap_vld : IN STD_LOGIC;
        simConfig_rowEnd_V_r_ap_vld : IN STD_LOGIC;
        simConfig_rowsToSimu_ap_vld : IN STD_LOGIC;
        simConfig_BLOCK_NUMB_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        output_r_TVALID : OUT STD_LOGIC;
        output_r_TREADY : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    grp_execute_fu_142 : component execute
    port map (
        input_V_data_TDATA => input_V_data_0_data_out,
        output_r_TDATA => grp_execute_fu_142_output_r_TDATA,
        output_r_TLAST => grp_execute_fu_142_output_r_TLAST,
        simConfig_rowBegin_V_2 => grp_execute_fu_142_simConfig_rowBegin_V_2,
        simConfig_rowEnd_V_r => grp_execute_fu_142_simConfig_rowEnd_V_r,
        simConfig_rowsToSimu => grp_execute_fu_142_simConfig_rowsToSimu,
        simConfig_BLOCK_NUMB => grp_execute_fu_142_simConfig_BLOCK_NUMB,
        size => size,
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        input_V_data_TVALID => grp_execute_fu_142_input_V_data_TVALID,
        input_V_data_TREADY => grp_execute_fu_142_input_V_data_TREADY,
        size_ap_vld => ap_const_logic_1,
        simConfig_rowBegin_V_2_ap_vld => ap_const_logic_1,
        simConfig_rowEnd_V_r_ap_vld => ap_const_logic_1,
        simConfig_rowsToSimu_ap_vld => ap_const_logic_1,
        simConfig_BLOCK_NUMB_ap_vld => ap_const_logic_1,
        ap_start => grp_execute_fu_142_ap_start,
        output_r_TVALID => grp_execute_fu_142_output_r_TVALID,
        output_r_TREADY => grp_execute_fu_142_output_r_TREADY,
        ap_done => grp_execute_fu_142_ap_done,
        ap_ready => grp_execute_fu_142_ap_ready,
        ap_idle => grp_execute_fu_142_ap_idle,
        ap_continue => grp_execute_fu_142_ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((output_V_tlast_V_1_ack_in = ap_const_logic_0) or (output_V_data_1_ack_in = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_execute_fu_142_ap_done_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_grp_execute_fu_142_ap_done <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_sync_reg_grp_execute_fu_142_ap_done <= ap_const_logic_0;
                elsif ((grp_execute_fu_142_ap_done = ap_const_logic_1)) then 
                    ap_sync_reg_grp_execute_fu_142_ap_done <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_grp_execute_fu_142_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_grp_execute_fu_142_ap_ready <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_sync_reg_grp_execute_fu_142_ap_ready <= ap_const_logic_0;
                elsif ((grp_execute_fu_142_ap_ready = ap_const_logic_1)) then 
                    ap_sync_reg_grp_execute_fu_142_ap_ready <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_execute_fu_142_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_execute_fu_142_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_sync_grp_execute_fu_142_ap_ready = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
                    grp_execute_fu_142_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_execute_fu_142_ap_ready = ap_const_logic_1)) then 
                    grp_execute_fu_142_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    input_V_data_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_V_data_0_sel_rd <= ap_const_logic_0;
            else
                if (((input_V_data_0_ack_out = ap_const_logic_1) and (input_V_data_0_vld_out = ap_const_logic_1))) then 
                                        input_V_data_0_sel_rd <= not(input_V_data_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    input_V_data_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_V_data_0_sel_wr <= ap_const_logic_0;
            else
                if (((input_V_data_0_ack_in = ap_const_logic_1) and (input_V_data_0_vld_in = ap_const_logic_1))) then 
                                        input_V_data_0_sel_wr <= not(input_V_data_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    input_V_data_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                input_V_data_0_state <= ap_const_lv2_0;
            else
                if ((((input_V_data_0_state = ap_const_lv2_2) and (input_V_data_0_vld_in = ap_const_logic_0)) or ((input_V_data_0_state = ap_const_lv2_3) and (input_V_data_0_vld_in = ap_const_logic_0) and (input_V_data_0_ack_out = ap_const_logic_1)))) then 
                    input_V_data_0_state <= ap_const_lv2_2;
                elsif ((((input_V_data_0_state = ap_const_lv2_1) and (input_V_data_0_ack_out = ap_const_logic_0)) or ((input_V_data_0_state = ap_const_lv2_3) and (input_V_data_0_ack_out = ap_const_logic_0) and (input_V_data_0_vld_in = ap_const_logic_1)))) then 
                    input_V_data_0_state <= ap_const_lv2_1;
                elsif (((not(((input_V_data_0_vld_in = ap_const_logic_0) and (input_V_data_0_ack_out = ap_const_logic_1))) and not(((input_V_data_0_ack_out = ap_const_logic_0) and (input_V_data_0_vld_in = ap_const_logic_1))) and (input_V_data_0_state = ap_const_lv2_3)) or ((input_V_data_0_state = ap_const_lv2_1) and (input_V_data_0_ack_out = ap_const_logic_1)) or ((input_V_data_0_state = ap_const_lv2_2) and (input_V_data_0_vld_in = ap_const_logic_1)))) then 
                    input_V_data_0_state <= ap_const_lv2_3;
                else 
                    input_V_data_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    output_V_data_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_V_data_1_sel_rd <= ap_const_logic_0;
            else
                if (((output_V_data_1_ack_out = ap_const_logic_1) and (output_V_data_1_vld_out = ap_const_logic_1))) then 
                                        output_V_data_1_sel_rd <= not(output_V_data_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    output_V_data_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_V_data_1_sel_wr <= ap_const_logic_0;
            else
                if (((output_V_data_1_ack_in = ap_const_logic_1) and (output_V_data_1_vld_in = ap_const_logic_1))) then 
                                        output_V_data_1_sel_wr <= not(output_V_data_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    output_V_data_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_V_data_1_state <= ap_const_lv2_0;
            else
                if ((((output_V_data_1_state = ap_const_lv2_2) and (output_V_data_1_vld_in = ap_const_logic_0)) or ((output_V_data_1_state = ap_const_lv2_3) and (output_V_data_1_vld_in = ap_const_logic_0) and (output_V_data_1_ack_out = ap_const_logic_1)))) then 
                    output_V_data_1_state <= ap_const_lv2_2;
                elsif ((((output_V_data_1_state = ap_const_lv2_1) and (output_V_data_1_ack_out = ap_const_logic_0)) or ((output_V_data_1_state = ap_const_lv2_3) and (output_V_data_1_ack_out = ap_const_logic_0) and (output_V_data_1_vld_in = ap_const_logic_1)))) then 
                    output_V_data_1_state <= ap_const_lv2_1;
                elsif (((not(((output_V_data_1_vld_in = ap_const_logic_0) and (output_V_data_1_ack_out = ap_const_logic_1))) and not(((output_V_data_1_ack_out = ap_const_logic_0) and (output_V_data_1_vld_in = ap_const_logic_1))) and (output_V_data_1_state = ap_const_lv2_3)) or ((output_V_data_1_state = ap_const_lv2_1) and (output_V_data_1_ack_out = ap_const_logic_1)) or ((output_V_data_1_state = ap_const_lv2_2) and (output_V_data_1_vld_in = ap_const_logic_1)))) then 
                    output_V_data_1_state <= ap_const_lv2_3;
                else 
                    output_V_data_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    output_V_tlast_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_V_tlast_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((output_V_tlast_V_1_ack_out = ap_const_logic_1) and (output_V_tlast_V_1_vld_out = ap_const_logic_1))) then 
                                        output_V_tlast_V_1_sel_rd <= not(output_V_tlast_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    output_V_tlast_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_V_tlast_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((output_V_tlast_V_1_ack_in = ap_const_logic_1) and (output_V_tlast_V_1_vld_in = ap_const_logic_1))) then 
                                        output_V_tlast_V_1_sel_wr <= not(output_V_tlast_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    output_V_tlast_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                output_V_tlast_V_1_state <= ap_const_lv2_0;
            else
                if ((((output_V_tlast_V_1_state = ap_const_lv2_2) and (output_V_tlast_V_1_vld_in = ap_const_logic_0)) or ((output_V_tlast_V_1_state = ap_const_lv2_3) and (output_V_tlast_V_1_vld_in = ap_const_logic_0) and (output_V_tlast_V_1_ack_out = ap_const_logic_1)))) then 
                    output_V_tlast_V_1_state <= ap_const_lv2_2;
                elsif ((((output_V_tlast_V_1_state = ap_const_lv2_1) and (output_V_tlast_V_1_ack_out = ap_const_logic_0)) or ((output_V_tlast_V_1_state = ap_const_lv2_3) and (output_V_tlast_V_1_ack_out = ap_const_logic_0) and (output_V_tlast_V_1_vld_in = ap_const_logic_1)))) then 
                    output_V_tlast_V_1_state <= ap_const_lv2_1;
                elsif (((not(((output_V_tlast_V_1_vld_in = ap_const_logic_0) and (output_V_tlast_V_1_ack_out = ap_const_logic_1))) and not(((output_V_tlast_V_1_ack_out = ap_const_logic_0) and (output_V_tlast_V_1_vld_in = ap_const_logic_1))) and (output_V_tlast_V_1_state = ap_const_lv2_3)) or ((output_V_tlast_V_1_state = ap_const_lv2_1) and (output_V_tlast_V_1_ack_out = ap_const_logic_1)) or ((output_V_tlast_V_1_state = ap_const_lv2_2) and (output_V_tlast_V_1_vld_in = ap_const_logic_1)))) then 
                    output_V_tlast_V_1_state <= ap_const_lv2_3;
                else 
                    output_V_tlast_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_V_data_0_load_A = ap_const_logic_1)) then
                input_V_data_0_payload_A <= input_V_data_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((input_V_data_0_load_B = ap_const_logic_1)) then
                input_V_data_0_payload_B <= input_V_data_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((output_V_data_1_load_A = ap_const_logic_1)) then
                output_V_data_1_payload_A <= grp_execute_fu_142_output_r_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((output_V_data_1_load_B = ap_const_logic_1)) then
                output_V_data_1_payload_B <= grp_execute_fu_142_output_r_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((output_V_tlast_V_1_load_A = ap_const_logic_1)) then
                output_V_tlast_V_1_payload_A <= grp_execute_fu_142_output_r_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((output_V_tlast_V_1_load_B = ap_const_logic_1)) then
                output_V_tlast_V_1_payload_B <= grp_execute_fu_142_output_r_TLAST;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, output_V_data_1_ack_in, output_V_data_1_state, output_V_tlast_V_1_ack_in, output_V_tlast_V_1_state, ap_CS_fsm_state4, ap_block_state4_on_subcall_done, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((output_V_tlast_V_1_ack_in = ap_const_logic_0) or (output_V_data_1_ack_in = ap_const_logic_0))) and (output_V_tlast_V_1_state(0) = ap_const_logic_0) and (output_V_data_1_state(0) = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state4_on_subcall_done_assign_proc : process(ap_sync_grp_execute_fu_142_ap_ready, ap_sync_grp_execute_fu_142_ap_done)
    begin
                ap_block_state4_on_subcall_done <= ((ap_sync_grp_execute_fu_142_ap_ready and ap_sync_grp_execute_fu_142_ap_done) = ap_const_logic_0);
    end process;


    ap_block_state5_assign_proc : process(output_V_data_1_ack_in, output_V_tlast_V_1_ack_in)
    begin
                ap_block_state5 <= ((output_V_tlast_V_1_ack_in = ap_const_logic_0) or (output_V_data_1_ack_in = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, output_V_data_1_ack_in, output_V_data_1_state, output_V_tlast_V_1_ack_in, output_V_tlast_V_1_state, ap_CS_fsm_state5)
    begin
        if ((not(((output_V_tlast_V_1_ack_in = ap_const_logic_0) or (output_V_data_1_ack_in = ap_const_logic_0))) and (output_V_tlast_V_1_state(0) = ap_const_logic_0) and (output_V_data_1_state(0) = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(output_V_data_1_ack_in, output_V_data_1_state, output_V_tlast_V_1_ack_in, output_V_tlast_V_1_state, ap_CS_fsm_state5)
    begin
        if ((not(((output_V_tlast_V_1_ack_in = ap_const_logic_0) or (output_V_data_1_ack_in = ap_const_logic_0))) and (output_V_tlast_V_1_state(0) = ap_const_logic_0) and (output_V_data_1_state(0) = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_grp_execute_fu_142_ap_done <= (grp_execute_fu_142_ap_done or ap_sync_reg_grp_execute_fu_142_ap_done);
    ap_sync_grp_execute_fu_142_ap_ready <= (grp_execute_fu_142_ap_ready or ap_sync_reg_grp_execute_fu_142_ap_ready);

    grp_execute_fu_142_ap_continue_assign_proc : process(ap_CS_fsm_state4, ap_block_state4_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            grp_execute_fu_142_ap_continue <= ap_const_logic_1;
        else 
            grp_execute_fu_142_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    grp_execute_fu_142_ap_start <= grp_execute_fu_142_ap_start_reg;
    grp_execute_fu_142_input_V_data_TVALID <= input_V_data_0_state(0);
    grp_execute_fu_142_output_r_TREADY <= ((output_V_tlast_V_1_ack_in and ap_CS_fsm_state4) or (output_V_data_1_ack_in and ap_CS_fsm_state4));
    grp_execute_fu_142_simConfig_BLOCK_NUMB <= 
        tmp_8_fu_308_p2 when (tmp_10_fu_284_p3(0) = '1') else 
        tmp_9_fu_314_p4;
    grp_execute_fu_142_simConfig_rowBegin_V_2 <= FirstRow(27 - 1 downto 0);
    grp_execute_fu_142_simConfig_rowEnd_V_r <= LastRow(27 - 1 downto 0);
    grp_execute_fu_142_simConfig_rowsToSimu <= 
        tmp_5_fu_273_p2 when (tmp_4_fu_239_p3(0) = '1') else 
        tmp_6_fu_263_p4;
    input_V_data_0_ack_in <= input_V_data_0_state(1);

    input_V_data_0_ack_out_assign_proc : process(grp_execute_fu_142_input_V_data_TREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_V_data_0_ack_out <= grp_execute_fu_142_input_V_data_TREADY;
        else 
            input_V_data_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    input_V_data_0_data_out_assign_proc : process(input_V_data_0_payload_A, input_V_data_0_payload_B, input_V_data_0_sel)
    begin
        if ((input_V_data_0_sel = ap_const_logic_1)) then 
            input_V_data_0_data_out <= input_V_data_0_payload_B;
        else 
            input_V_data_0_data_out <= input_V_data_0_payload_A;
        end if; 
    end process;

    input_V_data_0_load_A <= (input_V_data_0_state_cmp_full and not(input_V_data_0_sel_wr));
    input_V_data_0_load_B <= (input_V_data_0_state_cmp_full and input_V_data_0_sel_wr);
    input_V_data_0_sel <= input_V_data_0_sel_rd;
    input_V_data_0_state_cmp_full <= '0' when (input_V_data_0_state = ap_const_lv2_1) else '1';
    input_V_data_0_vld_in <= input_V_data_TVALID;
    input_V_data_0_vld_out <= input_V_data_0_state(0);
    input_V_data_TREADY <= input_V_data_0_state(1);
    output_V_data_1_ack_in <= output_V_data_1_state(1);
    output_V_data_1_ack_out <= output_r_TREADY;

    output_V_data_1_data_out_assign_proc : process(output_V_data_1_payload_A, output_V_data_1_payload_B, output_V_data_1_sel)
    begin
        if ((output_V_data_1_sel = ap_const_logic_1)) then 
            output_V_data_1_data_out <= output_V_data_1_payload_B;
        else 
            output_V_data_1_data_out <= output_V_data_1_payload_A;
        end if; 
    end process;

    output_V_data_1_load_A <= (output_V_data_1_state_cmp_full and not(output_V_data_1_sel_wr));
    output_V_data_1_load_B <= (output_V_data_1_state_cmp_full and output_V_data_1_sel_wr);
    output_V_data_1_sel <= output_V_data_1_sel_rd;
    output_V_data_1_state_cmp_full <= '0' when (output_V_data_1_state = ap_const_lv2_1) else '1';
    output_V_data_1_vld_in <= grp_execute_fu_142_output_r_TVALID;
    output_V_data_1_vld_out <= output_V_data_1_state(0);
    output_V_tlast_V_1_ack_in <= output_V_tlast_V_1_state(1);
    output_V_tlast_V_1_ack_out <= output_r_TREADY;

    output_V_tlast_V_1_data_out_assign_proc : process(output_V_tlast_V_1_payload_A, output_V_tlast_V_1_payload_B, output_V_tlast_V_1_sel)
    begin
        if ((output_V_tlast_V_1_sel = ap_const_logic_1)) then 
            output_V_tlast_V_1_data_out <= output_V_tlast_V_1_payload_B;
        else 
            output_V_tlast_V_1_data_out <= output_V_tlast_V_1_payload_A;
        end if; 
    end process;

    output_V_tlast_V_1_load_A <= (output_V_tlast_V_1_state_cmp_full and not(output_V_tlast_V_1_sel_wr));
    output_V_tlast_V_1_load_B <= (output_V_tlast_V_1_state_cmp_full and output_V_tlast_V_1_sel_wr);
    output_V_tlast_V_1_sel <= output_V_tlast_V_1_sel_rd;
    output_V_tlast_V_1_state_cmp_full <= '0' when (output_V_tlast_V_1_state = ap_const_lv2_1) else '1';
    output_V_tlast_V_1_vld_in <= grp_execute_fu_142_output_r_TVALID;
    output_V_tlast_V_1_vld_out <= output_V_tlast_V_1_state(0);
    output_r_TDATA <= output_V_data_1_data_out;
    output_r_TLAST <= output_V_tlast_V_1_data_out;
    output_r_TVALID <= output_V_tlast_V_1_state(0);
    p_neg6_fu_247_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(tmp_s_fu_233_p2));
    p_neg_fu_292_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(size));
    tmp_10_fu_284_p3 <= size(31 downto 31);
    tmp_4_fu_239_p3 <= tmp_s_fu_233_p2(31 downto 31);
    tmp_5_fu_273_p2 <= std_logic_vector(unsigned(ap_const_lv27_0) - unsigned(tmp_fu_253_p4));
    tmp_6_fu_263_p4 <= tmp_s_fu_233_p2(28 downto 2);
    tmp_7_fu_298_p4 <= p_neg_fu_292_p2(28 downto 2);
    tmp_8_fu_308_p2 <= std_logic_vector(unsigned(ap_const_lv27_0) - unsigned(tmp_7_fu_298_p4));
    tmp_9_fu_314_p4 <= size(28 downto 2);
    tmp_fu_253_p4 <= p_neg6_fu_247_p2(28 downto 2);
    tmp_s_fu_233_p2 <= std_logic_vector(unsigned(LastRow) - unsigned(FirstRow));
end behav;
