#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Fri Apr 17 16:14:28 CST 2020
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
echo "Before executing this script, make sure your already run the tcl file Run_my_design_Non_Project_Mode.tcl located at directory FPGA"
#ExecStep xvlog --incr --relax -work xil_defaultlib Netlist_Files/Top_FPGA_netlist.v TestBench/TestBench_Multi_FPGA.v -log compile.log

if [ ! -f ../FPGA/Netlist_Files/Top_FPGA_netlist.v ]; then
    echo "Netlist file not found in directory ../FPGA/Netlist_Files/!!!"
else
   xvlog --incr --relax -work xil_defaultlib Netlist_Files/Top_FPGA_netlist.v TestBench/TestBench_Multi_FPGA.v -log compile.log
fi
